### ISSUE TITLE
Requested locus in search bar - doesn't stop loading

### ISSUE THREAD

**Issue by MarkleLab** [igvteam/igv-webapp#100]
Hey, 

I am using the IGV Web app repo (pulling JS from a release tag for stability) and delivering it as a static resource in my Flask server. The contents of the igv-webapp are delivered in an iframe inside one of the pages of my application.

Its working great when I search for loci in the search bar inside the iframe. The issue is that sometimes (usually after about 20 searches but I'm not sure if the number has anything to do with it), the igvwebapp will keep loading the requested locus forever. Ultimately, causing Chrome to crash. 

First, I wanted to make sure that my own javascript wasn't causing these issues, so I've been diligently optimizing my code. Chrome doesn't crash anymore, so that was definitely me. But even after this, sometimes the loading for requested locus will take forever  :(

Second, I tried to deploy my Flask server to production. I read online that development servers can sometimes underperform, so I deployed a gunicorn server. Even on the production server I deployed, after a few searches, the loading for requested locus takes forever :(

To check if Flask itself was the issue, I also tried searching for loci on your deployed app igv.org/app and it works similarly, i.e. works great most of the time, but after a few consecutive searches, the loading starts taking forever.

I was hoping you could shed some light on this issue. And I wanted to thank you for responding so quickly to my previous questions. You've been really helpful! 🙂

And of course, please let me know if you need any more information or specifics! 

Best,
MarkleLab

**Comment by jrobinso** [comment]
Hi @MarkleLab,  thanks for the report.  Since you can reproduce it on igv.org/app let's focus on that.  Could you please give me exact steps to reproduce,  if possible, and generally more information.   For example what genome assembly, and what  types of files do you have loaded?     Steps to reproduce would be load XXX then do the following locus searches.....

We have a lot of public data for hg19,  look under the Tracks menu,  if you can create this isssue with that data it might be easier for me to reproduce.

**Comment by MarkleLab** [comment]
Hi @jrobinso,

Thanks for getting back!

The BAM data that originally caused this issue is private, so I can't share the exact files with you. I tried recreating the issue with the publicly available tracks on igv.org/app. I chose the Platinum Genomes track because we are interested in using IGV to view alignment data, and this track most resembles the kind of data we originally have (BAM).

The following was done in Google Chrome Version 74.0.3729.157 (Official Build) (64-bit)

**Genome**: Human (GRCh37/ hg19)
**Tracks**: Choose "Platinum Genomes." Select the following files: (first 5 in dropdown) NA12877, NA12878, NA12889, NA128990, NA12891.

I wasn't able to find a locus that truly freezes the browser on the public dataset, but some of the searches take way longer than the others. Some of them load in a few seconds, while others took much longer (see below for details). 

Here's the sequence of loci you can use to reproduce the issue:

This was on an **iMac running High OS Sierra v.10.13.6.** 
**Locus Searches**: 
chr1:231954045-231954045  # Takes about 7s for me.
chr9:34835361-34835361      # Takes about 6s for me
chr11:2664006-2664006        # Takes about 6s for me
chr11:2703116-2703116           # Takes about 5s for me
chr20:29628226-29628226   # Took about 1 min 30s.
chr20:29628229-29628229   # Took about 1 min 30s.
chr20:29628226-29628226   # Took about 1 min 30s.
chr20:29614272-29614272    # Took about 37s.
The loading time in the comments are averages of 3 runs of the entire sequence of loci. igv.org/app was reloaded before each run. 

This was on a **MacBook Pro running macOS Mojave V.10.14.4**. Runs same version of Google Chrome as noted above. 
**Same Locus Searches as above**: 
chr1:231954045-231954045  # Takes about 17s for me.
chr9:34835361-34835361      # Takes about 13s for me
chr11:2664006-2664006        # Takes about 12s for me
chr11:2703116-2703116           # Takes about 10s for me
chr20:29628226-29628226   # Took about 1 min 45s.
chr20:29628229-29628229   # Took about 1 min.
chr20:29628226-29628226   # Took about 2mins.
chr20:29614272-29614272    # Took about 1min 10s.
The loading times I report are averages of 3 runs of the entire sequence of loci. igv.org/app was reloaded before each run. 

It would be nice to know if there is a reason for this inconsistency in loading time between searches and that between systems. Similar pattern of wait times is experienced with my private BAM patient data when I embed igv.org/app inside my Flask app. The only difference is that on my own server, after about 2 minutes, the browser crashes ("Google Chrome has become unresponsive.").

I hope this was comprehensive and is therefore also reproducible on your systems, so this issue can actually be solved. Let me know if you need any more information at all, or have questions! 

Best,
MarkleLab

**Comment by jrobinso** [comment]
OK I will have a look.   I am on vacation until July 5, btw, might not be
until after then.

The times in your test seem to be increasing on average.   If you switch
the order of the test loci do you get similar results?   I wonder if the
specific loci are important or its just an accumulation.    If its just
increasingly after an accumulation we might have a memory leak.

Some loci have deeper coverage that others,  have you factored that in?
Most of the wait time should be loading the bytes over the network,  you
can check this in the network tab on chrome devtools.

**Comment by jrobinso** [comment]
Also,  BTW, loading 5 bams is going to stress the browser for memory,  but it should stress it consistently, not get worse over time.

**Comment by jrobinso** [comment]
OK,  sorry for the string of replies but I had a few minutes to try a couple of these.    I tried chr20:29614272-29614272  first which took 1 minute 17 seconds.   The average coverage here is around 700x.   I then tried chr1:231954045-231954045  which took 9 seconds.   The average coverage here is around 65.   That's a 10X difference in data and ~ a 10X difference in load time.

So for that particular case I don't think load order is a factor, and those times are not out of line for 5 deep coverage bams.   However, in your original report there was hint of some cumulative error,  where the system got slower over time and eventually crashed,  that isn't demonstrated yet with the platinum genomes but I will look at the possibility more deeply when I have more time.

**Comment by MarkleLab** [comment]
Hi @jrobinso,

Thanks for getting back! We had the same thoughts about this issue. This was either a loci-specific coverage/ mapping quality issue, or it was due to a memory leak. 

Like you recommended, I switched the order of the test loci. Here are the results for my iMac running High OS Sierra v.10.13.6.
Locus Searches (reverse order from original):
chr20:29614272-29614272 # Took about 45s.
chr20:29628226-29628226 # Took about 1 min 30s.
chr20:29628229-29628229 # Took about 1 min 30s.
chr20:29628226-29628226 # Took about 1 min 30s.
chr11:2703116-2703116 # Takes about 6s for me
chr11:2664006-2664006 # Takes about 6s for me
chr9:34835361-34835361 # Takes about 7s for me
chr1:231954045-231954045 # Takes about 10s for me.
The loading time in the comments are averages of 3 runs of the entire sequence of loci. igv.org/app was reloaded before each run.

There is no major hint of accumulation in these runs, so yes, I think this might be a coverage issue like you explain in your third comment, instead of a memory leak caused due to accumulation. This is only a few runs on my computer, but please do look at the possibility of accumulation in your code base more deeply when you have time.

However, if this is indeed only a coverage issue for specific loci, is there a way to check for massive loading times in IGV? These loading times are only going to increase in the coming years as BAM files get denser and denser as sequencing facilities advance their technology. 

Also, how did you know what the coverages (700x, or 65x) were? Would it be possible to know what the coverage is **before** I perform these searches? If I know the coverage beforehand, I can just query those searches in the native IGV app instead since that's much quicker. 

Thanks,
MarkleLab

**Comment by jrobinso** [comment]
@MarkleLab is 5 or more simultaneous bams typical for your typical use case?  If yes we'll have to optimize (reduce) memory usage wherever we can.   I see some potential options to do that which will be generally useful, but will require some new config parameters.

One option which is available now is to turn off high DPI support.   Support for highDPI screens require creating images 4X or more larger than non DPI screens.   High DPI support can be turned off with the following non-documented config option for the track
```
supportHiDPI: false
```
Could you try this for your BAM tracks?  Text will not look as sharp but it might solve or delay the crashing problem.   It would be interesting to know either way.   It will not affect load time, only memory usage.   Of course if you are not using a high DPI screen this will have no effect.

**Comment by jrobinso** [comment]
@MarkleLab emails are crossing.   There is no way to know coverage before loading from the BAM file alone.   I've been involved in NGS sequencing since it began,  dense high coverage regions have always been with us.   High coverage can occur at any time for even low average coverage bams.   Some regions of the genome just accumulate lots of reads (repeat regions for example).   This is why IGV downsamples reads by default, to prevent running out of memory.    What's unusual about your case is loading 5 bams at once,  this is atypical in general but we should be able to support it without crashing.   However you are going to wait while all that data is loaded over the network.

You mentioned that native IGV is much quicker for this case.   I haven't tried comparing these exactly yet,  but that would surprise me,  generally for the same BAMs and same regions times are roughly equal.

**Comment by jrobinso** [comment]
@MarkleLab another suggestion, if reviewing bams is your main use case check out igv-reports https://github.com/igvteam/igv-reports.   Its a python preprocessor that extracts bam alignments for a list of loci and packs them into the page itself as a data uri.   Using this would mean some redesign of your site obviously, but its really fast.

**Comment by MarkleLab** [comment]
Hi @jrobinso,

About 4-5 BAMs is typical for our use case. Thanks for the IGV Reports suggestion. It looks promising. I'll try to get it set up. And I will try the highDPI configuration, but our major concern right now is the load time. 

After seeing the loading times' trends, I don't think there's a major memory leak on your end or mine. But, do you think if we just used a different input file type, this problem might be solved? What is your experience with CRAM files, and do you think this might make loading faster since it stores data in a memory efficient manner? I know that IGV Webapp supports CRAM files already, but I don't have a lot of CRAM files to test loading times on. 

Thanks again for your help! 👍 

Best,
MarkleLab

**Comment by jrobinso** [comment]
@MarkleLab re load times, here is an experiment to determine the max possible we could achieve.  Do the same queries on the same files from the same computer with the command lines with ```samtools view```  or ```samtools tview```.   Use URLs not local file paths,  just as the app does.     This will take all the overhead of the web browser, javascript, and igv.js out of the equation.  

CRAM might faster, it would require experiments on the same files, and would depend on how agressively the CRAM file was compressed.

If you want fast loading preprocessing with igv-reports will give you the fastest possible load.  Out of the box it creates a complete page with a table view, but you don't have to use it that way.   There are APIs there to create the dataURIs.    These dataURIs can be used in place of urls in the config, its a straight replacement.   You don't supply an indexURL when using dataURIs.    See  examples/dataURI.html  (http://igv.org/web/release/2.2.13/examples/dataURI.htmll)
