### ISSUE TITLE
App doesn't launch - 404: "Not found" error

### ISSUE THREAD

**Issue by kubu4** [igvteam/igv-webapp#102]
After I start the app and then enter the URL (http://localhost:8080) in a browser (Brave, Firefox), nothing shows in the browser, but the terminal shows the following error message(s):

Brave error:

![20190730_002](https://user-images.githubusercontent.com/4514104/62143405-cb7f2980-b2a4-11e9-8513-ec7a9b3c9fb1.png)

---

Firefox error:

![20190730_001](https://user-images.githubusercontent.com/4514104/62143256-89ee7e80-b2a4-11e9-907a-b326b0c30d88.png)

---

Running this on Ubuntu 16.04 LTS.

Any tips on how to get this running? Thanks for looking into this!

**Comment by jrobinso** [comment]
Did you build the app first?

npm install
grunt

**Comment by kubu4** [comment]
Yes. Followed install instructions and then ran `npm start`.

Although, now that you mention it, running `grunt` did (and, still does) throw this error:

```grunt
No command 'grunt' found, did you mean:
 Command 'grun' from package 'grun' (universe)
grunt: command not found
```
I ran `npm install grunt`, thinking that would take care of the grunt problem. Maybe this is the underlying issue!

**Comment by jrobinso** [comment]
Yes that would be an issue (no grunt).   However "npm install" should have
installed it, its listed as a dev dependency,  but perhaps there's an issue
there.   Install grunt and grunt-cli,  to install it globally you might
need to do so as "sudo".

**Comment by kubu4** [comment]
Thanks. Will report back shortly (once I figure out how to install grunt and grunt-cli).

**Comment by kubu4** [comment]
Awesome! Thanks! That did it:

`sudo npm install -g grunt-cli`
`grunt`
`npm start`

Voila!

**Comment by iiiir** [comment]
@kubu4 , the exact steps does not seem to work for me

`$ npm install -g grunt-cli`      # i do not have sudo
Getting an error while running grunt command
`$ grunt`
```
grunt-cli: The grunt command line interface. (v0.1.11)
Fatal error: Unable to find local grunt.
```
did some google search and then tried:
`$ cd igv-webapp`
`npm install grunt --save-dev`

but now it asks for specific guntfile...
```
$ grunt
A valid Gruntfile could not be found. Please see the getting started guide for
more information on how to configure grunt: http://gruntjs.com/getting-started
Fatal error: Unable to find Gruntfile.
```

Not sure how to make a gruntfile that would work...

Thanks

**Comment by jrobinso** [comment]
@iiiir Grunt has nothing to do with this, its not even used anymore.

**Comment by iiiir** [comment]
@jrobinso ,thanks!
