### ISSUE TITLE
Default genomes list doesn't update

### ISSUE THREAD

**Issue by kubu4** [igvteam/igv-webapp#103]
I've edited the `resources/genomes.json` file to look like this:

```js
[
  {
    "id": "Pgenerosa_v070",
    "name": "Panopea generosa (v070)",
    "fastaURL": "http://owl.fish.washington.edu/halfshell/genomic-databank/Pgenerosa_v070.fa",
    "indexURL": "http://owl.fish.washington.edu/halfshell/genomic-databank/Pgenerosa_v070.fa.fai"
  }
]
```

---

I've also edited the `igvwebConfig.js` to look like this:

```js
/**
 * Configuration file for igv-webapp.   This is intentionally not a module so it can be used pre and post webpacking
 */

"use strict";

var igvwebConfig = {

    genomes: "resources/genomes.json",

    trackRegistryFile: "resources/tracks/trackRegistry.json",

    embedTarget: 'https://igv.org/web/release/2.2.14/embed.html',

    igvConfig:
        {
            genomeList: "resources/genomes.json",
            queryParametersSupported: true,
            showChromosomeWidget: true,
            showSVGButton: false,
            genome: ,

            // Supply a Google API key to access public Google resources.  This is optional.
            apiKey: "API_KEY"
        },

    // Supply a Google client id to enable the Google file picker in the load menus.  This is optional
    clientId: "CLIENT_ID",

    // Provide a URL shorterner function or object.   This is optional.  If not supplied sharable URLs will not
    // be shortened.
    urlShortener: {
        provider: "bitly",
        apiKey: "BITLY_TOKEN"
    }


};
```

---

Yet, when I launch the web app, hg19 is already loaded, the Genomes drop down menu is still populated with the default list, _and_ my custom genome is _not_ listed in the Genomes drop down menu.

Any help on why I can't eliminate the default genomes and/or load my custom genome would be great. Thanks for looking into this!

**Comment by jrobinso** [comment]
I'm not sure, but try giving a full URL to the genomeList property in
igv.confg.    If you're using http-server as described in the readme this
runs out of the "dist" directory,  so the url would e
http://localhost:8080/resources/genomes.json.   Check it in a web browser
to confirm.

**Comment by jrobinso** [comment]
Also,  if your editing anything in "resources" you need to run grunt after
editing as these get copied to the "dist" directory.   Verify that
dist/resources/genomes.json is as you expect.

Finally set "genome" in the igvConfig as described in the igv.js wiki.
For example

genome: "Pgenerosa_v070"

**Comment by jrobinso** [comment]
Give me a few days and I'll look into this more deeply.   I have some issues with IGV desktop and igv.js to attend to first.  It is my intent that this be customizable,  we'll get it to work.   Ping the issue again if there is a long delay.

**Comment by kubu4** [comment]
Thanks for the quick response!

Running `grunt` after editing the `resource/genomes.json` cleaned out the Genomes drop down list! Thanks.

Can't get the custom genome to show up, though. 

Thanks for looking into this! No rush, just wanted to try this out and see if we could get a customized, centralized IGV server running in the lab for everyone to use.

**Comment by jrobinso** [comment]
The answer to the question is yes,  that is exactly why we put it out there on github.   However I think the next step is for me to go through the exercise of customizing an install..   I'll do so by the end of the week,  we'll get it to work.

**Comment by kubu4** [comment]
Actually, the custom genome _does_ load! It just takes awhile, but there's no progress bar/loading indicator, so I didn't think anything was happening.

**Comment by iiiir** [comment]
@kubu4 , how your grunt file looks like? 
I am having the same issue, and the updated dist/resources/tracks/trackRegistry.json is NOT showing up in the dropdown list...

**Comment by jrobinso** [comment]
@iiiir Grunt has nothing to do with this, you are responding to an old ticket.  Your ticket is here: https://github.com/igvteam/igv-webapp/issues/133
