### ISSUE TITLE
http://igv.org/app - "Access Forbidden" pop up when loading FastA and FastA index from Google Drive

### ISSUE THREAD

**Issue by kubu4** [igvteam/igv-webapp#105]
When I try to load a genome FastA and corresponding FastA index from Google Drive (both files are publicly available), I get a pop-up box with the message "Access Forbidden".

Any thoughts on how to get around this?

**Comment by jrobinso** [comment]
You probably need a google access key,  but if you post the URLs below I will verify that.    What happens if you just paste those URLs in a browser address bar?

**Comment by kubu4** [comment]
If I paste the URLs to files, it shows me a page with a "Download" button.

FastA: https://drive.google.com/open?id=1ypc6kOts_PKXkLODkwqPxuPFNstbwWcl

FastA index: https://drive.google.com/open?id=10J7PCxJZx2sDgpzEqDkRMeJmxQPXSPoJ

Also, to clarify, I did not try to load these via URL. I selected the "Google Drive" option for loading a genome. When I do that option, I just browser Google Drive and select the files - no URLs are ever displayed.

**Comment by jrobinso** [comment]
Sorry for the delay in looking into this.   I verified that you need a Google API key to load these files, or any files on google drive apparently, in your web app.   We have one for use with igv.org, but when you download and install the web app on another server in Google's world its a different app.    This is one of the irritating things that makes Google hard to work with, if you have the choice of using Dropbox or Amazon S3 for your files you won't have this problem.

**Comment by kubu4** [comment]
> We have one for use with igv.org, but when you download and install the web app on another server in Google's world its a different app

To clarify, this error occurs when using igv.org. So, it seems like this is still an issue.

I have not tested with a locally installed version of the web app.

**Comment by jrobinso** [comment]
I can't reproduce this problem.  I can load your fasta files as a genome "by url".   I can't use the picker for your files since they are not on my drive,  but I can load other fastas with the google picker from my drive.

**Comment by kubu4** [comment]
Hmmmm. I'll stick with loading via URL then! Thanks for checking it out.
