### ISSUE TITLE
S3 api login

### ISSUE THREAD

**Issue by jamesthegiantpeach** [igvteam/igv-webapp#117]
Greetings,

If I have an S3 compatible API like minio with genomes on it, can I configure this application to login to an S3 api?

**Comment by jrobinso** [comment]
The short answer is I doubt it, but I don't know much about minio.

If this is a feature request please give us some details about your use case,  what file formats or web services you want to support, and generally how the workflow would look.   igv-webapp is a wrapper around the visualizer component igv.js, which is what I think you would want to use.   Review the documentation there on what's supported https://github.com/igvteam/igv.js/wiki.

**Comment by jamesthegiantpeach** [comment]
The use case is retrieving genomes via the S3 protocol. Is there any support for using the viewer with genomes in aws S3? If there is, then you’d just need a way to point to a specific S3 endpoint to use minio. The protocol is the same as aws S3

**Comment by jrobinso** [comment]
Sorry that's not a useful description,  what is a "genome" in your context?   Most of the files available in the webapp menus are hosted on Amazon S3.     

I think you need to review the documentation for igv.js carefully to see what is supported, then come back with specific questions.    At a high level minio is not supported out of the box, but probably doable with some work.

**Comment by jamesthegiantpeach** [comment]
Ok then it shouldn’t be too difficult to get this working with minio. The api is the same I would just need to figure out how to tell the viewer to use a specific S3 endpoint. I’ll read the docs and see if I can get it to work thanks.

**Comment by jrobinso** [comment]
Are your files in standard genomic formats (fasta, gff, etc)?

**Comment by jamesthegiantpeach** [comment]
Yes all standard formats

**Comment by jrobinso** [comment]
OK, yes doable then but it would take some work, mostly on igv.js not igv-web.  If you want to use s3:  urls you will need to first translate them to https or use the aws javascript sdk,  s3: is not an internet protocol browsers understand.   The translation to https for public buckets is straightforward.    If you want to use amazon authentication (e.g. cognito)  you will have to use the sdk.

**Comment by jamesthegiantpeach** [comment]
Ok I’m going to think about how to get this to work thanks for your help!

**Comment by jrobinso** [comment]
Good luck,  I can help if you get to the point of focused questions.   Sounds interesting.

**Comment by jrobinso** [comment]
Final thought, I notice the mino javascript api has a call to get a presigned URL.   That should be all you need.   Try getting a presigned url to one of your files and loading it in igv-webapp.
