### ISSUE TITLE
How to access the page

### ISSUE THREAD

**Issue by qkqk-hub** [igvteam/igv-webapp#118]
Hello! How can I access my page? I've now done this,
![图片](https://user-images.githubusercontent.com/54273704/67845702-edee4080-fb3a-11e9-844e-75f965536253.png)

 if I go directly to http://localhost:8081

The connection failed，
![图片](https://user-images.githubusercontent.com/54273704/67845783-0a8a7880-fb3b-11e9-8836-b648bb425c44.png)
 so what should I do next? What's wrong with me?Thank you！

**Comment by jrobinso** [comment]
You went to port 8080 in your screenshot, not 8081.

**Comment by qkqk-hub** [comment]
Thank you for your reply, but after I visited 8081, it still could not link to the page, why?
![图片](https://user-images.githubusercontent.com/54273704/67944241-f9169e80-fc16-11e9-8d5c-aaca00937f94.png)
![图片](https://user-images.githubusercontent.com/54273704/67944270-05026080-fc17-11e9-87a6-d4d051df027c.png)

**Comment by jrobinso** [comment]
Sorry I'm unable to read that message, but why are you starting this from an apache-tomcat directory?  It could certainly cause issues running apache-tomcat and http-server on the same computer especially if there are port conflicts.     That's just a guess.

**Comment by sjsachinrj** [comment]
@qkqk-hub  You need to hit http://localhost:8080/index.  In your case http://localhost:8081/index to access application

@jrobinso  It will be good  if you correct this startup URL in  README.md file

**Comment by helgathorv** [comment]
Some browsers require the /index in the URL to start the app - so I updated the readme as suggested.

**Comment by qkqk-hub** [comment]
Thank you for your reply. I see
