### ISSUE TITLE
load local fasta and gene annotation file as reference 

### ISSUE THREAD

**Issue by shihai832** [igvteam/igv-webapp#123]
Hi,

I am trying to add a local fasta and its gff3 file as reference. 
1) I clicked on the Genome->local File get the following error message "igvTest.genome.fa   ERROR: index file must also be selected".  Is index file required even for one contig fasta? My fasta file is one contig file  looks like
">sequence01 NODE_1_length_1770022_cov_224.147834
AGATTTCCCATAGCGTAAGCTAGTAAGATCCCTGAAAGATGATCAGGTTGATAGGTTCGA ...."

2) I clicked on the Tracks->Local file trying to load the gff3 file. Got the following alert "URL malformed". My gff3 file looks like 
"sequence01	BBTools	CDS	461955	463025	683	+	0	frame=2;startScr=1.309;stopScr=0.240;innerScr=0.300;start=TTG;stop=TGA"

3) Do i need to write a json file ./resources/tracks/ for my local ref genome and modify the ./resources/gemones.json manually?

4) Is there an APP in igv-webapp that create .genome file? Something similar to the one used in the desktop top IGV.

Thank you very much for your help.
shihai
B-10, Los Alamos National Lab

**Comment by helgathorv** [comment]
Hi,

1) Yes, the index is required for a one contig fasta.

2) I was not able to reproduce that error. Can you describe more specifically how you tried to load the file?

3) No, you do not need to update ./resources to have your own genome

4) We're moving away from the desktop .genome format. See the simpler .json format described [here](https://github.com/igvteam/igv.js/wiki/Reference-Genome). See the example in the doc. You can create a file like that in a text editor and make sure to give it the .json suffix, then read it into the IGV web app from the Genome menu. 

Helga

**Comment by helgathorv** [comment]
And to be clear, you don't HAVE to create a .json file to load your own genome; you can load the fasta and the gff3 separately, as I think you were already doing (based on your questions 1 and 2). 

Also, as you will see in the .json format documentation, it requires that the sequence and annotation files be available via URL - while the the .json file itself can be loaded from the local file system, it cannot refer to sequence and annotation files on the local file system.

**Comment by shihai832** [comment]
Thank you very much for your help. I am trying to load a gff3 file so I can display tracks., cds on localhsot:8081 using  igv.js. Attached three screen shots showing the steps and error I got. 

![step 1 use tracks button to load local gff3](https://user-images.githubusercontent.com/57105074/72384260-4c5aa200-36da-11ea-82b9-19e190046228.png)
![step 2 choose gff3 fiel loacaly and press ok](https://user-images.githubusercontent.com/57105074/72384264-4f559280-36da-11ea-974f-e3aedf089be2.png)
![step 3 error message](https://user-images.githubusercontent.com/57105074/72384271-52e91980-36da-11ea-8ad3-d3b68a378702.png)

**Comment by jrobinso** [comment]
This is strange indeed.   I assume you clicked the "local file" button to get that dialog   Would it be possible to zip up that directory and attach it here?  We can give you a dropbox link to upload it to if you would prefer.  We need to try to reproduce this.

**Comment by jrobinso** [comment]
Also, as you are running locally what version of igv.js are you using?  Have you just pulled the latest from master?

**Comment by shihai832** [comment]
Please provide the drop box link as email says it is too large to send.

Thanks,
shihai

**Comment by jrobinso** [comment]
Here you go.  Let us know when you upload and we will disable the link  https://www.dropbox.com/request/cfeUlTQWAxakpOESaWcI

**Comment by shihai832** [comment]
Jim,

File loaded. Thank you very much for your help. Please feel free to call me
at my office 5056679910.

Thanks,
shihai

**Comment by jrobinso** [comment]
Got it.  I can reproduce the problem with that gff.  Will update here when its fixed.

**Comment by shihai832** [comment]
Thanks a lot.

Shihai

**Comment by jrobinso** [comment]
@shihai832 The root of the problem is your gff file is not valid gff3.  Among other problems, commas need to be escaped in column 9, and values should not be quoted (although the quotes do not does not cause an error, the presence of the unescaped commas does).  The spec is here:  https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md

What software created this gff file?

The error message from igv.js is not very helpful here,  I will be working on that tomorrow.

**Comment by shihai832** [comment]
Thank you very much. I will clean it up.

Shihai

**Comment by shihai832** [comment]
The same gff3 file works on the desktop version of IGV. Just FYI

Shihai

**Comment by helgathorv** [comment]
Hi Shihai,

Thanks for the additional info. But when I load your full gff3 file (downloaded from dropbox) into IGV 2.8.0 desktop on Mac OS I get an error: 
_Error loading /Users/helga/Downloads/asmbl_rename.gff3: URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: " i"_

**Comment by shihai832** [comment]
I used creat . genome option to include the gff3 as Gene file. I didn't
load it directly.

Shihai

**Comment by shihai832** [comment]
Jim,

Problem solved with

sed  's/\%/\%25/g' asmbl_rename_original.gff3 | sed s/\,/\%2C/g  | sed
's/"//g'  | sed  's/\&/%26/g' > asmbl_rename.gff3.


Thank you very much.


shihai

**Comment by jrobinso** [comment]
@shihai832 Thanks for letting me know.  The parser in igv.js is stricter than IGV desktop, however  I am relaxing the parser in igv.js, since we do nothing with the attributes in column 9 this level of strictness is not required.
