### ISSUE TITLE
ability to add tracks from google bucket paths

### ISSUE THREAD

**Issue by bw2** [igvteam/igv-webapp#125]
It would be great if I could load crams, etc. from google buckets via gs:// paths.

**Comment by jrobinso** [comment]
@bw2 you can, are you having problems?

**Comment by bw2** [comment]
I tried adding a non-public path via Load URL.. but nothing happened.

**Comment by jrobinso** [comment]
If you can share that with me by private email I'll look into it.   gs://
urls are used by many people (Terra for example).

**Comment by jrobinso** [comment]
@bw2 Are you using igv.org/app for this?  To access a private google resource of any kind, you need a google client_id.   If you're trying to run this from your own host you'll have to obtain one.  Even a public google resource requires an api key.   There are plenty of Google people there at the Broad that could help you do this.

**Comment by bw2** [comment]
I was just using https://igv.org/app/.  When I put in a gs:// url it doesn't prompt me to login, so I just assumed it wasn't supported.

**Comment by jrobinso** [comment]
@bw2 if you send me the URL you were trying I'll look into it.

**Comment by jrobinso** [comment]
@bw2 Not sure if there is an issue here or not, if there is please re-open.
