### ISSUE TITLE
npm start will not run

### ISSUE THREAD

**Issue by shihai832** [igvteam/igv-webapp#126]
bash-3.2$ npm install
audited 4342 packages in 1.902s

7 packages are looking for funding
  run `npm fund` for details

found 98 vulnerabilities (97 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
bash-3.2$ npm start

> igv-webapp@1.1.0 start /Users/shihai/Desktop/IGV_JS/igv-webapp-master
> http-server -a localhost dist

Starting up http-server, serving dist
Available on:
  http://localhost:8080
Hit CTRL-C to stop the server
[2020-03-09T20:33:08.641Z]  "GET /" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:68.0) Gecko/20100101 Firefox/68.0"
(node:32056) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
[2020-03-09T20:33:08.648Z]  "GET /" Error (404): "Not found"

**Comment by jrobinso** [comment]
@shihai832 did you have a question or issue?

**Comment by shihai832** [comment]
yes sir,

I tried to npm install and start igv-webapp got the following error message.
bash-3.2$ npm i acorn@^7.0.0
+ acorn@7.1.1
added 1 package and audited 4342 packages in 2.343s

7 packages are looking for funding
  run `npm fund` for details

found 98 vulnerabilities (97 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
bash-3.2$ npm install
audited 4342 packages in 1.902s

7 packages are looking for funding
  run `npm fund` for details

found 98 vulnerabilities (97 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
bash-3.2$ npm start

> igv-webapp@1.1.0 start /Users/shihai/Desktop/IGV_JS/igv-webapp-master
> http-server -a localhost dist

Starting up http-server, serving dist
Available on:
  http://localhost:8080
Hit CTRL-C to stop the server
[2020-03-09T20:33:08.641Z]  "GET /" "Mozilla/5.0 (Macintosh; Intel Mac OS X
10.15; rv:68.0) Gecko/20100101 Firefox/68.0"
(node:32056) [DEP0066] DeprecationWarning:
OutgoingMessage.prototype._headers is deprecated
[2020-03-09T20:33:08.648Z]  "GET /" Error (404): "Not found"
[2020-03-09T20:37:09.320Z]  "GET /" "Mozilla/5.0 (Macintosh; Intel Mac OS X
10.15; rv:68.0) Gecko/20100101 Firefox/68.0"
[2020-03-09T20:37:09.322Z]  "GET /" Error (404): "Not found"

Please help. My machine is macOS Catalina V10.15.3

Thanks,
shihai

**Comment by turner** [comment]
1) Does the website run properly when you type: npm start
2) I cannot reproduce the messeges you see when you quit the server via CTRL-C.

**Comment by shihai832** [comment]
/Users/shihai/Desktop/IGV_JS/igv-webapp-master

bash-3.2$ npm start


> igv-webapp@1.1.0 start /Users/shihai/Desktop/IGV_JS/igv-webapp-master

> http-server -a localhost dist


Starting up http-server, serving dist

Available on:

  http://localhost:8080

Hit CTRL-C to stop the server


But there is no window pops on either in chrome or firefox.


shihai

**Comment by jrobinso** [comment]
DId you click the link?  http://localhost:8080

**Comment by shihai832** [comment]
after I pasted the "http://localhost:8080" to browser, I got the following
error:
"
[2020-03-10T20:16:04.330Z]  "GET /" "Mozilla/5.0 (Macintosh; Intel Mac OS X
10.15; rv:68.0) Gecko/20100101 Firefox/68.0"
(node:43316) [DEP0066] DeprecationWarning:
OutgoingMessage.prototype._headers is deprecated
[2020-03-10T20:16:04.335Z]  "GET /" Error (404): "Not found"
^Chttp-server stopped."

**Comment by turner** [comment]
I cannot reproduce the issue you are seeing

**Comment by shihai832** [comment]
yes. I clicked the link. The website is totally blank on firefox and has
error message says "This localhost page can’t be found" on chrome.

shihai

**Comment by jrobinso** [comment]
@shihai832 Sorry we can't reproduce this problem, we've tried from multiple machines, however we have not tried on Catalina as we don't have Catalina installed.  It could be that http-server does not work on Catalina.

**Comment by jrobinso** [comment]
Some folders such as "Documents" are privileged on Catalina,  you might try creating a new directory off your home directory and install it there.

**Comment by shihai832** [comment]
I installed it on my desktop. It runs fine on my old mac though.

shihai

**Comment by jrobinso** [comment]
Yes, like I said, I think its a problem specific to Catalina.  Desktop is also a priveleged folder on Catalina.  Could you try as I suggested and let us know the result?  Create a folder (directory) somewhere other than Documents or Desktop and install there.   Please let us know the result so we can alert others.

Web searching http-server on Catalina might bring up useful suggestions.

**Comment by turner** [comment]
I have tested on Mac Catalina 10.15.3 and it works fine.

**Comment by turner** [comment]
I have tested in a restricted folder as well. No issues.

**Comment by jrobinso** [comment]
OK, thanks @turner .

**Comment by shihai832** [comment]
Thanks a lot. I will try. Shihai

**Comment by shihai832** [comment]
How do I tell it to use port localhost:3000. I can't get localhost:8080
working.

shihai

**Comment by turner** [comment]
npx http-server -a localhost -p 8888 dist

**Comment by jrobinso** [comment]
@shihai832 Your questions are really about http-server,  you can find documentation here:  https://www.npmjs.com/package/http-server

**Comment by shihai832** [comment]
I tried to run igv on localhost:3000 which I know I can run other program
on. I get the same error messages. The following is what I did.

I git clone the igv-webb to ~/ and npm install then "npx http-server -a
localhost -p 3000 dist", I got:

bash-3.2$ npx http-server -a localhost -p 3000 dist

Starting up http-server, serving dist

Available on:

  http://localhost:3000

Hit CTRL-C to stop the server


I copied and pasted  http://localhost:3000 to chrome,  got "This localhost page
can’t be found" on web site. on terminal:


[2020-03-11T16:36:46.798Z]  "GET /" "Mozilla/5.0 (Macintosh; Intel Mac OS X
10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130
Safari/537.36"

(node:48852) [DEP0066] DeprecationWarning:
OutgoingMessage.prototype._headers is deprecated

[2020-03-11T16:36:46.805Z]  "GET /" Error (404): "Not found"

**Comment by jrobinso** [comment]
@shihai832 As we've stated many times we can't reproduce your problem, and in any event it is an http-server problem.   Please post your issues there.

**Comment by shihai832** [comment]
ok. Thanks for your time anyway.

shihai

**Comment by shihai832** [comment]
I promise this my last email regarding this issue if you want.  I just want
to help other users who may run into the same problems.

I am able to run older version igv-webapp on my catalina.  I believe I got
it around 01/12/2020. I can't attached it in my email due to gmail security
concern. It is the latest version I got this week from the github gives me
problems. Just FYI. Right now, I am fine with issue closed.

Thanks,
shihai

**Comment by jrobinso** [comment]
@shihai832 Thanks that's good information.  It would have been helpful to tell us that at the beginning.   Could you try pulling from this commit and see it it has the problem?  That will narrow it down.   There has been only 1 commit since 1/12/2020  cd35dce5ca5b8168ec1403c30f104b1f0a950fe9

**Comment by shihai832** [comment]
i just tried to use the older version today. But it seems I still have the
same problem. The follow is what I did. I am not sure if got the cd35dce
correctly.

shihai@pn2001085 igv-webapp % rm node_modules

rm: node_modules: is a directory

shihai@pn2001085 igv-webapp % rm -r node_modules

shihai@pn2001085 igv-webapp % git checkout cd35dce

HEAD is now at cd35dce update license

shihai@pn2001085 igv-webapp % npm install

shihai@pn2001085 igv-webapp % npm start


> igv-webapp@1.1.0 start /Users/shihai/igv-webapp

> http-server -a localhost dist


Starting up http-server, serving dist

Available on:

  http://localhost:8082

Hit CTRL-C to stop the server

[2020-03-11T20:58:26.807Z]  "GET /" "Mozilla/5.0 (Macintosh; Intel Mac OS X
10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130
Safari/537.36"

**Comment by jrobinso** [comment]
OK, you have some local problem on your machine, I don't think that has anything to do with igv-webapp per se.   Look for things that changed on your computer since you were last able to run this.   You might also try http-server with something else (not igv-webapp).
