### ISSUE TITLE
Not loading google bucket links

### ISSUE THREAD

**Issue by AlexdeMendoza** [igvteam/igv-webapp#129]
Dear IGV app developers, 

I have been using a IGV-Browser app session with plenty of sessions linked to a public Google cloud bucket. It used to work fine, but now it says "Error loading data" in every single track. When trying exactly the same "gs:" path in the IGV Desktop app, it loads it and there is not a problem.

Are you aware of any issue like that affecting other users?

I can give you links to the files if necessary. 

Thanks in advance for your help. 

Best,

Alex

**Comment by jrobinso** [comment]
No, not aware of any issues.  Look at the network tab to see what the responses are for those requests.   Also what version are you using, and have you updated versions recently?  Our last release was on November 9.

**Comment by AlexdeMendoza** [comment]
Sorry, I am using: https://igv.org/app/, and loading the files directly there (Tracks -> URL ...).

**Comment by AlexdeMendoza** [comment]
I might be missing something very obvious, but I cannot find the network tab in the website version.

**Comment by jrobinso** [comment]
Are these private files?  I don't personally have a billable account, so I can't make private test files in a gs bucket, but if you could create one and authorize me I can test it.  Public gs:// files are loading fine.   If you are able to do this send email to igv-team (at) broadinstitute.org and we can work out details there.

**Comment by jrobinso** [comment]
I can't reproduce the problem.  If you can share a URL with me that's not working please re-open the ticket.
