### ISSUE TITLE
loading files local to the igv-webapp

### ISSUE THREAD

**Issue by mattdmem** [igvteam/igv-webapp#130]
Hello,

I was wondering if it would be possible to load bams from a dir local to the igv web app (i.e. on the server)? or do I have to serve these?

Thanks

Matt

**Comment by jrobinso** [comment]
You can use the menu to load them.   You can't use a path (file url or
otherwise),  that is not allowed in a web app.

**Comment by mattdmem** [comment]
Thanks... I get this.... however, is there no workaround? The webserver can see all of the bams, so is there a way of populating a drop down or something that would load a selected bam? I guess the only way is to provide users with a link that directs the browser to the served file?

**Comment by jrobinso** [comment]
I'm not sure what you are asking.     What webserver?

If the file is loadable by URL then of course you can provide the user a
link.   If you want to scan directories from your webserver and build a
menu that is possible, but would require custom coding.

**Comment by chenlin0802** [comment]
For example: a server  installed this igv-webapp,  and there is also a bam file on this server with path /data/xxx/xxx/xx.bam .   Add a menu using server path directly, but not download from the server to local at first as now.

**Comment by jrobinso** [comment]
@chenlin0802  First of all igv-webapp is a client application, it has nothing to do with a server, it runs 100% on the client web browser.  I assume you understand that just pointing it out.   Given that I don't really understand what you are suggesting.

**Comment by jrobinso** [comment]
Closing this.   See my answer to #138
