### ISSUE TITLE
no effect after changing resources/genomes.json

### ISSUE THREAD

**Issue by iiiir** [igvteam/igv-webapp#133]
Hi,
Sorry for the naive question. I really want to get this work but have not been successful after try many times.

I was able to set up igv-webapp.
By running 
`npm start` I can get it running. However I have two issues:
1. except hg19 (the default?), everything else will give error:
![image](https://user-images.githubusercontent.com/4137873/79183788-4fdbf300-7dc7-11ea-8417-04cdb53a8490.png)

2. I cannot change any of the genome list (or the track lists):
I modified my `resources/genomes.json` to by deleting all other genomes:
![image](https://user-images.githubusercontent.com/4137873/79183896-9c273300-7dc7-11ea-987c-a85066f0fba1.png)

but the genome drop down menu will not change. 

similarly i modified `resources/tracks/trackRegistry.json`, and will not have effects.

Thank you very much,
Shuoguo

**Comment by iiiir** [comment]
@jrobinso , I still have issue, but thought I published at wrong repo...tried to follow a resolved issues but still having trouble:
https://github.com/igvteam/igv-webapp/issues/103

thanks for the quick response.

**Comment by jrobinso** [comment]
Are you restarting your server (http-server) after editing the json?

**Comment by jrobinso** [comment]
If you are running from the dist directory you need to rebuild after making any changes with

>npm run build

From the root directory.   Then restart.

**Comment by iiiir** [comment]
yes. i re-run `npm run build`  `npm start` every time.

feel like i should just update `resource/genome.json` and `resource/tracks/trackRegsitry.json`, followed by  `npm run build` and  `npm start`

I see the genome drop down menu changed, but not the tracks drop down menu. will test a bit more

**Comment by jrobinso** [comment]
You can just edit the files in dist/resources, instead of resources, and avoid the build step.  I just updated the readme to reflect that.

**Comment by iiiir** [comment]
Does this looked good?
`$ vi igvwebConfig.js`

![image](https://user-images.githubusercontent.com/4137873/79191912-88d29280-7ddc-11ea-8666-a1b36ae77ef9.png)

`$ vi dist/resources/genomes.json`
![image](https://user-images.githubusercontent.com/4137873/79191760-31ccbd80-7ddc-11ea-99f5-6726cd71a4e5.png)

`$ vi dist/resources/tracks/trackRegistry.json`
![image](https://user-images.githubusercontent.com/4137873/79191720-19f53980-7ddc-11ea-88d8-d954764205e5.png)

Thanks,

**Comment by jrobinso** [comment]
I think those paths should be relative to the webpage referencing them, correct?  In that case you should not have "dist/" in them.   What are you seeing in the javascript console, or network tab?
