### ISSUE TITLE
Suggest: shortURL using Google FireBase Dynamic Links

### ISSUE THREAD

**Issue by sbamin** [igvteam/igv-webapp#140]
I am trying out igv-webapp for our intranet. Looking great so far and thanks for sharing this app. One suggestion though for shortURLs. I believe google shorturl is [now deprecated over firebase dynamic links](https://developers.googleblog.com/2018/03/transitioning-google-url-shortener.html) and bitly seems unstable. It would be better if you can have user-supplied API token for either tinyURL or better, google firebase dynamic link. That way, shorturls are more private and restricted by user supplied api token.

I have been using firebase api for while and it's stable to generate shareable urls. [Here is a bash wrapper](https://gist.github.com/sbamin/8721452a9d0ceff28461d44aca693620) to generate urls (where FBXK is an api token field). I will tinker with java script to add firebase links at somepoint but thought would be quicker on your end. 

https://github.com/igvteam/igv-webapp/blob/0a013c9a7c1c2dd1e9760ee72331545584cc1278/js/urlShortener.js#L47-L61

**Comment by jrobinso** [comment]
We are happy with tinyURL.  If you wish to customize your own installation I will consider a pull request to make this customizable, that was actually the intent originally.

**Comment by sbamin** [comment]
Sure and will do that sometime later in June. Thanks again - just setup functional igv portal and using [caddy OAuth2 plugin](https://caddyserver.com/v1/docs/http.login) for secure access.
