### ISSUE TITLE
Invalid index file

### ISSUE THREAD

**Issue by cssulliv** [igvteam/igv-webapp#141]
Hi!

I am currently trying to upload my .bam and .bai mapping files and .fa file on the web app. I keep getting errors saying that the mapping files are invalid. The mapping files have the same name but have a different name than the genome fasta file. I hope to upload more read mapping files from other samples that have mapped to this genome but am unable to because of the `invalid file` error. 

I also wanted to note that the stand alone IGV version is able to upload and view the mapping and fasta files but due to RAM conflicts I am unable to view 2 samples (2.bam files) at a time. 

I am happy to send an email containing a .zip file of the mapping and fasta files. (I am unable to upload them here as the file size is large).

Best,
Clarisse

**Comment by jrobinso** [comment]
Yes I will need a zip example to look into this, along with a step by step
description of what you are doing.  Be as specific as possible.

BTW technically you are not uploading anything,  the files are loaded
directly into your browser.
