### ISSUE TITLE
Error loading Track data

### ISSUE THREAD

**Issue by tstbio** [igvteam/igv-webapp#143]
Hi,
I am Computational  scientsit in a sequencing plateform.

I just installed igv-webapp on our server.
Our server in on a secure network only accessible with a vpn client.

**I can acess IGV and load file from my computer, but when i go to the page I have the following message : **

[Thu May 28 2020 12:41:04 GMT+0200 (GMT+02:00)]  "GET /" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
[Thu May 28 2020 12:41:04 GMT+0200 (GMT+02:00)]  "GET /css/app.css.map" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
[Thu May 28 2020 12:41:04 GMT+0200 (GMT+02:00)]  "GET /igv.css.map" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
[Thu May 28 2020 12:41:04 GMT+0200 (GMT+02:00)]  "GET /css/app.css.map" Error (404): "Not found"
[Thu May 28 2020 12:41:04 GMT+0200 (GMT+02:00)]  "GET /igv.css.map" Error (404): "Not found"
 
I made sure that the user rights are OK.

 My real problem is the following:

I tried to open a bam file with the following URL (Both the igv-webapp and the bam +( bam.bai) are on the same server) :

http://**IP**:8080/?load?genome=hg19&file=http://**IP**:8080/users/home/MYBAM.bam

**When i zoom in i get the following error:**

"Error loading Track data"

**My web browser show me this error:**

igvxhr.js:260 GET http://**IP**/users/home/MYBAM.bam.bai 404 (Not Found)

bamSource.js:157 Error: 404
    at b (igvxhr.js:268)
    at igvxhr.js:240
    at tryCatch (app_bundle.js:56)
    at Generator.invoke [as _invoke] (app_bundle.js:276)
    at Generator.prototype.<computed> [as next] (app_bundle.js:109)
    at $r (runtime.js:725)
    at o (runtime.js:725)
    at runtime.js:725
    at new Promise (<anonymous>)
    at XMLHttpRequest.<anonymous> (runtime.js:725)

**and my consol give me this one :**

"GET /users/home/MYBAM.bam Error (404): "Not found"

I also update CORS but thats not working and it is not suppose to be relevant (if I understood correctly)

I really need to be able to open the BAM file  via URL, to make our analysts work easier.

Thanks a lot and i hope not to be redondant with other issues but I didn't find thi specific problem.

Thanks a lot,

Tristan

**Comment by tstbio** [comment]
Thanks for your answer Jim, and sorry for the false repository. 

I don't really understand the 404 error, as I can download my bam when I put my file URL into my web browser.

Regarding the load of the index file, when i try to load an index file with the URL, I get the message 
"Unknown type of file  http://IP:mybam.bam.bai". 

Could you please give me an exemple URL for IGV web apps?

Thanks again,

Tristan

**Comment by jrobinso** [comment]
Did you really mean file URL (file://)?  A file URL has nothing to do with it.  You need to but the URL igv-webapp is using in the browser, specifically http://IP:mybam.bam in you example.

Where is your bam file in relation to your webserver root directory?    And what exactly are you entering at the URL  (the exact string)?

Here's an example
```
https://s3.amazonaws.com/1000genomes/phase3/data/HG00096/exome_alignment/HG00096.mapped.ILLUMINA.bwa.GBR.exome.20120522.bam.cram
https://s3.amazonaws.com/1000genomes/phase3/data/HG00096/exome_alignment/HG00096.mapped.ILLUMINA.bwa.GBR.exome.20120522.bam.cram.crai
```

**Comment by tstbio** [comment]
Thanks for the links Jim, I managed to resolve my problems.

Severals Things :

1) I had to allow CORS access in my apache configuration ( httpd in my case, because I work on an CentOs server) in the **'<Directory "/var/www/html">'** block.
    **AllowOverride All 
    Header set Access-Control-Allow-Origin "*"
    Header set Access-Control-Allow-Methods: "GET,POST,PUT,OPTIONS"
    Header set Access-Control-Allow-Headers: "RANGE, Cache-control, If-None-Match, Content-Type"
    Header set Access-Control-Expose-Headers: "Content-Length, Content-Range, Content-Type"**

2) I was using bam file and not cram file (bams don't work for me)

3) Indeed i wasn't giving the index file in my URL

http://**IGV_SERVER_ADRESSE**/?load?genome=hg19&index=http://**MY_IP**/CRAM1.cram.crai&file=http://**MY_IP**/CRAM1.cram

My CRAM.cram and CRAM.cram.crai are located in my /var/www/html/ folder on my server and my IGV_SERVER_ADRESSE is http://**MY_IP**:8080

Thanks again for the support Jim

Tristan

**Comment by tstbio** [comment]
Thanks so much. That was the problem.

In my apache configuration /etc/httpd/conf/httpd.conf  in the '<Directory "/var/www/html">' block I just added the line :

**AddType application/octet-stream .bam**

Thanks for your support.

Tristan
