### ISSUE TITLE
Need example BED file

### ISSUE THREAD

**Issue by bosborne** [igvteam/igv-webapp#146]
I'm having no luck uploading my own genome (*fa, *fai) and BED file to https://igv.org/app/ ("Local file" option). The genome appears, but not the track.

You know what would be useful? An example BED file that works, like "ecoli.bed" to go along with "ecoli.fa" and "ecoli.fa.fai", in the genomes/ dir.

**Comment by jrobinso** [comment]
Could you zip and attach an example bed that is not working for you?

**Comment by bosborne** [comment]
Yes Jim.

[test.zip](https://github.com/igvteam/igv-webapp/files/4820850/test.zip)

And thank you for the offer.

**Comment by jrobinso** [comment]
The sequence names in your bed file do not match the names in your fasta.
 In the bed file it is "1".   In the fasta it is NC_004718.3

**Comment by bosborne** [comment]
Got it. No documentation I read mentioned that. UCSC, Sanger.

**Comment by jrobinso** [comment]
The first column is the name of the "chromosome or scaffold" (per UCSC).
In practice this means the sequence in your fasta file, which is usually a
chromosome but doesn't have to be.
