### ISSUE TITLE
Feature request: import tracks from web-app host storage

### ISSUE THREAD

**Issue by olavurmortensen** [igvteam/igv-webapp#149]
This is a feature request. If someone knows a way I could implement this myself, for example by forking this repository, I would be happy to hear this as well.

Basically, I'm trying to use IGV web-app to visualize data on our high-performance compute cluster storage. So I want to install IGV web-app on a machine on the server, this part is easy. Getting the IGV web-app to get access to data on the server's storage, however, is not easy.

The "Local file ..." option in the "Tracks" menu opens a file on the local machine. I wonder if there is a way to run the web-app where you load a file from the path on the *host system*, the host being the machine on our server that is running the IGV web-app.

If this seems like an unrealistic retrofitting of the IGV web-app, please let me know.

Any help is much appreciated.

**Comment by jrobinso** [comment]
First I don't understand what you are trying to accomplish by running the
web-app on a server.   The web-app runs in a browser, are you running the
browser on a server?  How is the user viewing it, via a remote desktop of
some kind?

WRT accessing files, you can't use local file paths as strings at all in a
web application,  it requires that the user take explicit action and use
the OS file browser to locate the file.   This is a security requirement of
web browsers, nothing can be done about it other than perhaps using Chrome
specific extensions.

You can run a web server, e.g. apache, nginx, even http-server or flash,
and load files by URL.   Is this what you are envisioning?

**Comment by iiiir** [comment]
I think I had the same initial business purpose:
after pipeline finishes --> generate a igv-web link for each sample --> review data by clicking on the link

benefits:
saves time locating/loading data
can directly set url to certain regions for review, no need to type in chr:start-end
e.g. desired results: http://igv-wepapp/xxxx?file=/dir/to/sample1.bam&?type=bam&?pos=chr1:12345-12346

hope you can figure out and share the solution.

**Comment by olavurmortensen** [comment]
Thanks for the quick response @jrobinso 

> The web-app runs in a browser, are you running the browser on a server? 

The app runs on the server, broadcasts it via a port on the server's IP address. 

> How is the user viewing it, via a remote desktop of some kind?

The user opens the browser at `[ servers IP]:[ port that web-app runs on]`. The same way you might run Jupyter or RStudio Server, if you are familiar with these applications.

> First I don't understand what you are trying to accomplish by running the web-app on a server.

Viewing genetic data that is on our server, and that for security reasons must not leave the server. Our server does not use GUIs, only terminal, and occasionally web-apps, which is why I'm not using the normal IGV application.

> You can run a web server, e.g. apache, nginx, even http-server or flash, and load files by URL.   Is this what you are envisioning?

I don't quite understand. What is the purpose of, for example, the Apache server?

**Comment by jrobinso** [comment]
@olavurmortensen the purpose of the Apache server was to serve data to the webapp.   I don't understand how you are going to get this to work with a "local file" object, but I don't fully understand your architecture.   To restate your original question

_**I wonder if there is a way to run the web-app where you load a file from the path on the host system?**_

I don't understand the question, I assume you understand how "local files" work in a web browser, but if not here is a short synopsis.   The web browser allows users to browse the local file system using the OS file browser.  They can select a file, which is exposed to javascript as an opaque Blob object.   Javascript can never know the path to the file,  it can only interact with this Blob obtained from the file browser button interaction.   

Good luck with this, I'm going to close it as an issue as I don't see anything we can do for you.

**Comment by iiiir** [comment]
Just a quick comment to share how I load local data, as igv-webapp itself have the http function
e.g. save your save under /dir/to/igv-webapp/**data**/sample1.bam
then for trackregistry set to the http link to the bam file:
vi dist/resources/tracks/hg19_test.json
...
"url": "http://your-server-ip-address/**data**/sample1.bam",
...

There could be better solutions but I got thus far

**Comment by jrobinso** [comment]
@iiiir that is not a local file in the strict sense,  you are using http-server (a web server) to serve the files by relative URL.  That is exactly what I was suggesting using a web server for.   The node http-server is a web server, but would not be my first recommendation for a production system.

**Comment by millerh1** [comment]
Hi @jrobinso I would also like to request this feature... I get the impression from the conversations here that you are imagining people will want to use IGV web app as a public-facing web app, but actually many people want to use it as a private interface for viewing their own alignment files on their HPC (there's currently nothing which allows this AFAIK and it's a huge burden). Typically, the HPC is only accessible within some kind of secure VPN, so we are mostly unconcerned with the security risk potential.

Currently, it is not possible to view the .bam files on my HPC in IGV without downloading the whole thing from the HPC --- which can take hours... 

So it sounds like you are saying we need to do this:

Make a .bam file on remote server --> Download .bam file onto PC (takes long time and requires storage on PC) --> Connect to remote server IP address at specified port in a browser --> upload .bam file to IGV web app session on remote server (takes long time) --> view .bam file alignments

What we are asking for is this:

Make a .bam file on remote server --> Connect to remote server IP address at specified port in a browser --> select .bam file from remote server filesystem (using some kind of "load file from server" option) --> view .bam file alignments

Rstudio server and Jupyter notebook server both offer this capability so it is a bit unclear to me why IGV web app couldn't do the same. 

@iiiir has a nice work-around but certainly not ideal for convenience

**Comment by jrobinso** [comment]
@millerh1 First of all, I suspect most users who download the webapp will do so for private web apps.   I don't see the motivation for others to host a public igv-webapp as we already do that.    We are aware of a number of private installations on secure intranets.

I don't understand your contention that you have to download a bam file,  you don't,  but you do have to be able to mount the remote file system or have a URL to the file.   The simplest solution is to host a web server.   Jupyter notebook server is a web server,  I don't know what Rstudio is.  

I am not following your suggestion from a technical perspective,  yes it would be possible to build such a system by developing a custom webserver on the backend to handle the interactions, but that is outside the scope of igv-webapp.   As a pure javascript client direct interactions with file systems, local or remote, is not possible.   If it were it would be a huge security hole, as you can imagine.   For individual users who want to browse their files we  offer IGV desktop app.   As a desktop application it has access to the filesystem.
