### ISSUE TITLE
Missing branches in package.json dependencies 

### ISSUE THREAD

**Issue by martina-g** [igvteam/igv-webapp#150]
Hi, 
I'm installing the igv-webapp. 
After cloning the repo, as suggested in the README file, I run `npm install` but I get the following error:
```
npm ERR! Command failed: git checkout 0.2.2
npm ERR! error: pathspec '0.2.2' did not match any file(s) known to git.
```
The package.json dependencies:
```
  "dependencies": {
    "data-modal": "github:igvteam/data-modal#0.2.2",
    "igv-ui": "github:igvteam/igv-ui#0.1.1",
    "igv-utils": "github:igvteam/igv-utils#0.1.0",
    "igv-widgets": "github:igvteam/igv-widgets#0.1.2"
  }
```
but could not find the branch `0.2.2` for the `data-modal `repo, neither the other repo branches needed by npm.
I solved by linking the master branches for all dependencies required and run `npm install` + `npm run build `+` npm start ` with success.

The package.json dependencies now looks like this
```
  "dependencies": {
    "data-modal": "github:igvteam/data-modal",
    "igv-ui": "github:igvteam/igv-ui",
    "igv-utils": "github:igvteam/igv-utils",
    "igv-widgets": "github:igvteam/igv-widgets"
  }
```
I'd like just to be sure this is correct.
Thank you in advance.

**Comment by jrobinso** [comment]
@martina-g Yes it was a mistake in our package.json,  the temporary fix you implemented will work fine.  We will push an update with the correct tags soon.
