### ISSUE TITLE
Save SVG function not working

### ISSUE THREAD

**Issue by sonnyarora** [igvteam/igv-webapp#158]
Hi,

When I go to the IGV webpage https://igv.org/app/ and click "Save SVG" in the banner and click "ok" in the modal, nothing happens. When I look in the console,  I see the following error:

app_bundle.js:10728 Uncaught TypeError: browser.renderSVG is not a function
    at HTMLButtonElement.okHandler (app_bundle.js:10728)
    at HTMLButtonElement.dispatch (jquery-3.3.1.slim.min.js:2)
    at HTMLButtonElement.v.handle (jquery-3.3.1.slim.min.js:2)

I'm using Google Chrome. Let me know if there's something I'm missing. Thanks in advance!

Best,

Sonny

**Comment by jrobinso** [comment]
Thanks for calling that to our attention.   I will need to fix it on our
side.

**Comment by jrobinso** [comment]
This is working now.
