### ISSUE TITLE
Drosophila dm6 RefSeq genes missing

### ISSUE THREAD

**Issue by marianolabrador** [igvteam/igv-webapp#162]
I'm using the IGV genome browser online and the RefSeq annotation track does not show the genes anymore. It's been like this for a few days. You can still use the Ensembl Genes but the reference gene name is cumbersome to use.
thanks

**Comment by helgathorv** [comment]
We just fixed some issues with the reference genomes today. Can you clear your browser cache and try again.

**Comment by jrobinso** [comment]
@marianolabrador Yes we noticed this ourselves this morning.   Its fixed now.   Please don't hesitate to report problems, they get fixed faster when we are aware of them.   Thanks.

**Comment by marianolabrador** [comment]
Great! it works now.
thanks


Mariano Labrador, PhD
Associate professor
Department of Biochemistry & Cellular and Molecular Biology
The University of Tennessee
Knoxville, TN 37996
labrador@utk.edu<mailto:labrador@utk.edu>
Office: 865  974-3690
Lab:  865  974-3790

________________________________
