### ISSUE TITLE
include fission yeast genome

### ISSUE THREAD

**Issue by mah11** [igvteam/igv-webapp#163]
Greetings,

Could the fission yeast (*Schizosaccharomyces pombe*) genome be included in the selection of genomes available IGV-Web at https://igv.org/app/?

PomBase, the model organism database for *S. pombe*, makes the genome sequence available in FASTA format (downloadable from ftp://ftp.pombase.org/pombe/genome_sequence_and_features/genome_sequence/Schizosaccharomyces_pombe_all_chromosomes.fa.gz). Please let us know if there's anything else you would need to be able to add the genome.

I'm doing this as a GitHub issue so I can tag Val Wood (@ValWood), who is the PomBase project manager and who has worked on the *S. pombe* genome since before its completion, in case you have any questions about the genome status.

(Note: I found this thread on the igv-help group: https://groups.google.com/forum/#!msg/igv-help/KjExkCACVWg/yfw5KGCeZpAJ It hasn't seen any activity since April 2013, but requested essentially the same thing. If you use the genome file from PomBase it will avoid the issues with Ensembl Fungi versions raised in the old thread. The actual sequence used by the *S. pombe* community has not changed since 2008.)

Many thanks,
Midori Harris, Database Curator, PomBase

**Comment by jrobinso** [comment]
Hi,  Midori

Yes this should be doable.  Do you suggest any particular annotation files in addition to the fasta?   Perhaps the files here?  ftp://ftp.pombase.org/pombe/genome_sequence_and_features/gff3/

**Comment by mah11** [comment]
Yes, it would be great if you can include the files in that directory -- they have the genes and other annotated sequence features. As with the FASTA sequence, the all_chromosomes file should have everything you need.

**Comment by jrobinso** [comment]
And what should it be labeled in the menu?  Sorry for such pedantic questions but its easier to ask than guess.

**Comment by mah11** [comment]
No problem; it's fantastic to have such a quick response. I think "S. pombe (ASM294v2)" would work for the menu.

**Comment by jrobinso** [comment]
OK this was straightforward, but I can't release it for a few days.   If this isn't out by Friday please ping this issue again.

**Comment by jrobinso** [comment]
@mah11 S. Pombe is now in the menu, near the bottom.   Let me know if you spot issues.

**Comment by mah11** [comment]
@jrobinso I didn't see this before the weekend due to the time difference, but it looks fine. Thank you!
