### ISSUE TITLE
Tracks: Google drive and ENCODE 

### ISSUE THREAD

**Issue by niallghowlett** [igvteam/igv-webapp#164]
Hi - up until very recently, you could access google drive files and ENCODE datasets through the Tracks tab, at least for hg19. Have these features been removed? These were really useful features of the IGV web app.
Niall
(nhowlett@uri.edu)

**Comment by jrobinso** [comment]
Apologies for that,  I just restored Google Drive access, give it a try.  You might have to clear your browser cache, I did.

We're looking into the ENCODE problem but we will get it restored.

**Comment by niallghowlett** [comment]
I just tried and google drive access is restored. Thanks! Looking forward to having ENCODE access restored.

**Comment by niallghowlett** [comment]
Hi. I'm just following up on the ENCODE access through tracks issue, thanks.

**Comment by helgathorv** [comment]
We're planning to release later today.

**Comment by jrobinso** [comment]
Encode is restored.  There are now 2 menus for each assembly, "Signals" and "Other".  Signals is all the bigWig tracks.   The sheer number had gotten too large for some browsers.

**Comment by niallghowlett** [comment]
Awesome. Thank you!
