### ISSUE TITLE
No Data / Shows empty Screen

### ISSUE THREAD

**Issue by RoAsad** [igvteam/igv-webapp#177]
Hi, when I opened up your website (https://igv.org/app/) this morning, it's showing a screen with no data in it? Is it an issue from your server?

**Comment by helgathorv** [comment]
It's working for me right now. But I have occasionally seen that same blank screen and clearing the browser cache helped, and so did switching to a different different browser.

**Comment by jrobinso** [comment]
@RoAsad What web browser are you using?

**Comment by RoAsad** [comment]
I am using google chrome. I cleared the browser cache and now it's working fine. Thank you for your help.
