### ISSUE TITLE
IGV WEB - Dropdown menu is not visible

### ISSUE THREAD

**Issue by tahuh** [igvteam/igv-webapp#179]
Hi team.

I have installed this application on my ubuntu 18.04 laptop machine and building was successful.

But when I try navigate 'Genomes', the end of dropdown menu is not visible on my web browser as shown below.

I'm using firefox as my browser and screen resolution is 1360 x 768 (16:9).

Does IGV webapp require certain resolution or minimum size of screen? (My screen size is 15.6 inches)

Thanks

![igv_genome_scrolls](https://user-images.githubusercontent.com/12674567/96560345-26ad9980-12f9-11eb-9d62-474f4f38852e.png)

**Comment by jrobinso** [comment]
I see the entire dropdown, what do you mean "the end is not shown"?

**Comment by jrobinso** [comment]
There should be a scrollbar on the web browser itself,  but I don't see it (on the right).   I'll see if we can reproduce this here.

**Comment by jrobinso** [comment]
Yes we can reproduce this.    We will work on a solution.   In the meantime you can get around this by editing "genomes.json" in the "dist/resources" directory.     Remove any genome entries that are not of interest.   Judging from your screen removing 4 or 5 should be enough.

**Comment by tahuh** [comment]
@jrobinso 

Thanks for you fast reply.

I have changed genomes.json file in dist/resources directory and restart http-server, but the 'Genomes' drop down menu did not change.

I have re-cloned this repository and changed contents of resorces/genomes.json file in cloned directory and then built this application and no changed applied.

To test if my machine has problem, I have moved onto new windows laptop with WSL2.

Again, I have cloned this repo, changed contents of resources/genomes.json under cloned repo and then build the app.

The change not but if I change the resources/genomes.json under `dist` directory, nothing happens.

I have tried to launch application both `dist` or `cloned igv-webapp` directory with command as in README file.

Is there any solution about this or am I doing something wrong?

Thanks in advance.

**Comment by jrobinso** [comment]
If you rebuild the app then genomes.json will get copied from /resources to /dist/resources,  so to be safe change in in both locations.   Also clear you browser cache.    If you use developer tools look for the "genomes.json" request in the network tab and verify it is getting it from where you are expecting it, and look at the response.   Everything is configurable here,  but it should be getting it from the location I specified.

**Comment by jrobinso** [comment]
Ahh, hold on, there might be a problem here in the latest code.   It seems to be getting it from amazon irrespective of local settings.    I'm looking at it now.

**Comment by jrobinso** [comment]
Actually, false alarm, it works as expected.  I see 2 loads of genomes.json, 1 from igv-webapp and one from igv.js.   The igv.js load is for internal use and does not affect the menu.   After removing all genomes except "hg38" from genomes.json this is what I see.   

<img width="280" alt="Screen Shot 2020-10-20 at 7 16 39 PM" src="https://user-images.githubusercontent.com/933148/96665135-10a7d500-1309-11eb-8fba-5391d10b4a14.png">

**Comment by jrobinso** [comment]
Depending on how and from where you start your webserver,  it might pickup dist/resources/genomes.json or resources/genomes.json,  to be safe edit both.   Otherwise you'll need to look in the network tab to see what's going on.  You will see 2 loads of a file called "genomes.json",  1 from an amazon host and 1 from you local system.  Ignore the amazon load, it is not relevant,  you can verify the path to the local one and also the response.

**Comment by tahuh** [comment]
Hi @jrobinso 

Thanks for reply!

I tried to change both location file but now worked but after clearing cache worked.

I think we can close this thread.

Thanks!

**Comment by jrobinso** [comment]
Ahh, good. I should have mentioned clearing the cache, for some reason browsers often don't detect changes to .js and .json files.
