### ISSUE TITLE
Local BAM file does not have index file

### ISSUE THREAD

**Issue by tahuh** [igvteam/igv-webapp#180]
Hi team.

I'm loading my BAM file using 'Tracks -> Locals...' but the application complains that index file is missing

![INDEX_FAIL](https://user-images.githubusercontent.com/12674567/96682879-638a9680-13b4-11eb-9d0d-95391cdbbbad.png)

I have checked my system and found there is BAM and BAI files are properly located.

![Screen_Shot](https://user-images.githubusercontent.com/12674567/96682951-7e5d0b00-13b4-11eb-87ba-27fc613c2772.png)

Is there any reason?

I could  successfully open that BAM file on stand-alone IGV.

**Comment by jrobinso** [comment]
Did you select both the BAM and the Index file?

**Comment by jrobinso** [comment]
The message is confusing, but when loading local files with IGV-Webapp you have to select both the bam and its index file.    The file dialog allows selection of multiple files.  This is necessary because web browsers do not allow our application to know the actual path to the file, to do so would be a security problem.

**Comment by tahuh** [comment]
@jrobinso 

That makes sense.

Thanks for your advice and it works!

It would be better for community if you leave a comment on README file about this situation for end users, because some of community members are not familiar with how the network goes or browser works etc..

Thanks

**Comment by jrobinso** [comment]
We will add an explanatory note to the error dialog.  It is already in the user documentation, although we recognize that many don't read docs.  https://igvteam.github.io/igv-webapp/
