### ISSUE TITLE
Dropbox link is not working

### ISSUE THREAD

**Issue by aardes** [igvteam/igv-webapp#190]
Dear IGV Team,

The Dropbox links in the Genome and Track menu items is not working.

https://igv.org/app/

Uncaught ReferenceError: Dropbox is not defined
    MultipleTrackFileLoad https://igv.org/app/app_bundle-1.4.1.js:16799

Kind regards
Amin

**Comment by helgathorv** [comment]
Thanks for letting us know. We'll look into it asap.

**Comment by jrobinso** [comment]
This is fixed, thanks again for the report.

**Comment by aardes** [comment]
Thanks for the fast fix.
