### ISSUE TITLE
Could not resolve igv.esm.js

### ISSUE THREAD

**Issue by sonnyarora** [igvteam/igv-webapp#193]
Hi,

I was looking to install igv-webapp from source. I'm working on Centos 7, with Node v10.23.0, npm version 6.14.8. I followed the instructions on the github page. npm install returned no errors. When I run npm run build, I get:

> igv-webapp@1.4.3 build /home/sza149/igv-webapp-custom/igv-webapp
> node scripts/updateVersion.js && node scripts/clean.js && rollup -c && node scripts/copyArtifacts.js

js/app.js → dist/app_bundle-1.4.3.js, dist/app_bundle-1.4.3.min.js...
[!] Error: Could not resolve '../node_modules/igv/dist/igv.esm.js' from js/app.js
Error: Could not resolve '../node_modules/igv/dist/igv.esm.js' from js/app.js
    at error (/home/sza149/igv-webapp-custom/igv-webapp/node_modules/rollup/dist/shared/rollup.js:5253:30)
    at ModuleLoader.handleResolveId (/home/sza149/igv-webapp-custom/igv-webapp/node_modules/rollup/dist/shared/rollup.js:18403:24)
    at Promise.all.Array.from (/home/sza149/igv-webapp-custom/igv-webapp/node_modules/rollup/dist/shared/rollup.js:18372:22)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! igv-webapp@1.4.3 build: `node scripts/updateVersion.js && node scripts/clean.js && rollup -c && node scripts/copyArtifacts.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the igv-webapp@1.4.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sza149/.npm/_logs/2020-12-02T18_05_13_701Z-debug.log

Any ideas what could be going on? Let me know if you need more details. Thanks in advance.

Best,

Sonny

**Comment by jrobinso** [comment]
Did you run "npm install" prior to "npm run build"?

**Comment by jrobinso** [comment]
Sorry I see you did.   I'm not sure why its looking for "igv.esm.js",  there should be no dependency on igv.js.   Checking now.

**Comment by jrobinso** [comment]
Should be fixed now

**Comment by sonnyarora** [comment]
Works, thank you!
