### ISSUE TITLE
Sequence track missing while loading non-default genomes

### ISSUE THREAD

**Issue by zqfang** [igvteam/igv-webapp#194]
I could only see sequence track the very first time when I open my browser (default genome is mm10).

![image](https://user-images.githubusercontent.com/5889336/101662870-de5c4f00-39fe-11eb-8d07-a756147ed4fa.png)

However, when I would like to try other genomes, the sequence track is no longer exist. Is there a good way to load it manually, instead of uploading a local file?

**Comment by helgathorv** [comment]
Thanks for letting us know - I can see there is indeed a problem. We'll investigate ...

**Comment by helgathorv** [comment]
@zqfang This has now been fixed in the IGV-Web app at igv.org/app

**Comment by zqfang** [comment]
@helgathorv , Thank you! That was fast
