### ISSUE TITLE
Local fasta file loading

### ISSUE THREAD

**Issue by martina-g** [igvteam/igv-webapp#199]
Hi,
I’m willing to make my IGV browser load local fasta files. I’d like to have this functionality in the webpage where the user sets some of the input values (`genref`, `locus`, `url`, `filename`) which are then sent to the my IGV browser page to populate the `options` variable.
I know the igv-webapp  has a navbar component “Genome” which allows to load local files. 
So, I’ve installed a copy of the IGV webapp locally to look for the piece of code responsible for the local file loading so that I can import it and adapt it in my project. When I open the menu Genome, select “Local file…” and choose a fasta + fai files, I get the warning “There are no tracks in the track registryy for genome ${genomeID}”. 
The warning is given in file `node_modules/igv-widgets/dist/igv-widgets.js`, in function 
```
updateTrackMenus() {
	[..]
	const paths = await getPathsWithTrackRegistryFile(genomeID, trackRegistryFile);

	if (undefined === paths) {
    		console.warn(`There are no tracks in the track registryy for genome ${genomeID}`);
    		return;
	}
	[..]
}
```
The `paths` variable is `undefined`.
For what I see, it is not enough to select fasta+fai in the Local file element.
Am I right? What am I missing? How could I reach my goal?

Thank you in advance for your help.

**Comment by jrobinso** [comment]
That is a warning, not an error.   It means there will be no tracks
available for this genome.

**Comment by martina-g** [comment]
ah okay, thank you :-)
Is there a function that allows to import the local genome file loader functionalities in a custom IGV browser?
I don't know if this is the right place to ask since it is not an IGV issue, but mine :-)  
thank you for your help

**Comment by jrobinso** [comment]
Sorry I don't understand the question.

**Comment by martina-g** [comment]
I'm sorry, I was not clear enough.
The igv browser is instantiated in `viewer.html`
```
<body>
     <div id="igvDiv">
          [..]
    </div>
    <script type="module">

    const server_url = localStorage.getItem("serverurl");
    const filename = localStorage.getItem("filename");
    const igvLocus = localStorage.getItem("igvLocus");
    const genref = localStorage.getItem("genref");

    import igv from "./igv_lib/js/index.js";
    var options =
        {
            genome: genref,
            locus: igvLocus,
            tracks: [
                {
                    type: 'alignment',
                    sourceType: 'htsget',
                    format: 'bam',
                    url: server_url,
                    name: filename,
                    endpoint: '/sample',
                    coverageTrackHeight: 50
                }
            ]
        };
    var igvDiv = document.getElementById("igvDiv");
    igv.createBrowser(igvDiv, options)
        .then(function (browser) {
            console.log("Created IGV browser");
            window.igvBrowser = browser;
        })
     </script>
</body>

```
The variables server_url, filename, igvLocus and genref are set in index.html. 
For example genref is set as follows:
```
<body>
    <form action="" id="genrefForm">
         <h5 class="">
              Select reference genome
         </h5>
         <div class="input-field col s12 l6">
            <select id="selectGenref" name="genref">
                 <option value="" disabled selected></option>
                 <option value="hg38">hg38</option>
                 <option value="hg19">hg19</option>
                 <option value="hg18">hg18</option>
              </select>
             <div> Add local reference genome
                 // modal to load fasta + fai
                // in js script, read fasta + fai
                      // set local genome name
                      // genref = "myGenref';
                     //  localStorage.setItem("genref", genref );
            </div>
            <div class="col s12 l6">
                <button id="btnLocalGenref" class="btn blue" type="submit"> submit</button>
            </div>
         </form>
    [..]
    <script type="text/javascript">
    var host = "http://localhost:8080";
    $.getJSON(host + "/samples", function(){
        localStorage.setItem("genref", "hg19" );
        var grform = document.getElementById('genrefForm');
        grform.onsubmit = function(e) {
            e.preventDefault();
            var genref = grform.genref.value;
            if (genref) {
                localStorage.setItem("genref", genref );
            } 
        }
    </script>
</body>
```
I'd need to implement the `<div>Add local reference genome </div>` section and, once in `viewer.html,` making the IGV browser read and load the local genome.
Is it complex to implement? 
Hope this is much clearer now..
Thank you for your help

**Comment by martina-g** [comment]
Nevermind, I've found the solution in the `reference object`+ its 'fastaURL' property.
Thank you for your time, I really appreciated your quick response.

**Comment by jrobinso** [comment]
Ah yes, that is perhaps confusing, but ```fastaURL```, and for that matter all properties that end with ```URL```,  can take a File blob as a value.

**Comment by YichaoOU** [comment]
Hello,

I'm not good at javascript. Would you mind sharing the code how to use `File blob` to load local fasta file?

Thanks,
Yichao

**Comment by jrobinso** [comment]
All the code is in the repository, however to load a local file you just use the Genome menu.
