### ISSUE TITLE
Load tracks from server file system

### ISSUE THREAD

**Issue by fangpingmu** [igvteam/igv-webapp#201]
I am running IGV-web through Open Ondemand. Each user will request resources (several cores for several hours) on a HPC cluster to run his own IGV-web server. 

Under Tracks, I can only load file from my local computer, Dropbox or a URL.

Because each user will run his own server, it makes more sense to load his own files from the server. Under Tracks, I would like a menu item "Server File ..." to load files from server. Is this possible?

Is it possible to add server files to URL...? I have tried file:///<local file location> and this does not work.

**Comment by jrobinso** [comment]
You cannot load from the file system in javascript on a web browser by specifying any kind of path, including file:// urls.  That would be a huge security hole.  To load from the file system requires user interaction, specifically opening a file browser for them to choose as "Load from file" does.   Even after this, that path to the file is opaque to javascript.

**Comment by fangpingmu** [comment]
Thank you. This javascript property makes sense. 

https://github.com/OSC/bc_js_filepicker

OSC has this form.js to navigate into a directory on the computer running IGV-webapp. Is it possible to add "Load Server File ..." using this form.js? 

I am not familiar with javascript. Even if you answer yes, I may not be able to implement it. I am just curious.

**Comment by jrobinso** [comment]
I am not familiar with that, and don't have time to study their javascript,  in any event these are not IGV questions they are generic web development questions, you might try a more general forum.

**Comment by fangpingmu** [comment]
Thank you. I am closing this issue.
