### ISSUE TITLE
Accessing igv.js's "browser" object?

### ISSUE THREAD

**Issue by whole-systems-enterprises** [igvteam/igv-webapp#205]
Hi. igv-webapp is great software. When I load index.html into a window, how do I access the igv.js component's browser object from javascript? A crude hack is to make the variable global but that is inelegant and I figure you might have a better method? Thanks!

**Comment by jrobinso** [comment]
This really isn't part of the igv-webapp design, for an embeddable component see https://github.com/igvteam/igv.js.     When you say "make the variable global" I'm not sure what you are referring to, but attaching the "browser" object to a global is one solution.  You will note its attach to a "Globals" variable in line 83 of js/app.js, but that is not truly "global" its scope is within the app.     However after building the es5 compatible package that variable should be accessible though the global "igv_webapp",  so this might work

```
igv_webapp.Globals.browser
```

This is also a hack, I'm not sure its any better than your solution and I haven't tried it, just looking at the rollup config file.
