### ISSUE TITLE
MUT file support not available from local file upload

### ISSUE THREAD

**Issue by feedlord18** [igvteam/igv-webapp#206]
igv.js supports MUT file however it has not been supported for "local file" -> upload

**Comment by jrobinso** [comment]
mut file support is not released in igv.js yet, and is not supported in igv-webapp (yet).    I will be wrapping up support for both projects this week.

**Comment by feedlord18** [comment]
gotcha. In the meantime, would you be able to point me to the file where the webapp handles local file imports?

**Comment by feedlord18** [comment]
Hi. Just wanna follow up for any updates on this.

**Comment by helgathorv** [comment]
@feedlord18 We just released versions of igv.js and igv-web that support MUT files.
