### ISSUE TITLE
Directory on a Server into an accessible?

### ISSUE THREAD

**Issue by gpcr** [igvteam/igv-webapp#210]
We have installed IGV-webapp on a internal server; 

How to make users access Directory (bam and reference files) on the Server (where igv-webapp installed: not local ) into an accessible when using through web ?
 
This helps to avoid big bam files to be copied to local machine and then access it.

Thanks

**Comment by jrobinso** [comment]
I'm not sure I understand your question.    Is the "users access Directory" accessible on the server where igv-webapp is installed?

**Comment by gpcr** [comment]
Yes, Bams are located in the server,  need to access from multiple user computers

**Comment by jrobinso** [comment]
I'm not sure why the users computers are relevant, but if you want to serve those bams you can either run a webs server, such as apache, for them or use the server that hosts igv-webapp.   If the latter you could use symbolic links.  Questions about general web server development and setup can best be answered eslewhere, or by a web search.

**Comment by jrobinso** [comment]
@gpcr BTW I am closing this as its not an issue or bug, but feel free to ask more questions here.
