### ISSUE TITLE
Failed to load module script: Expected a JavaScript module igv-widgets.js:1

### ISSUE THREAD

**Issue by feedlord18** [igvteam/igv-webapp#214]
I did a clean pull from master branch. Running on NPM 7.17.0 and node 12.18.4. Did the following:
1. npm install
2. npm run build
All successful but when I run the server, I get this in Chrome console. "Failed to load module script: Expected a JavaScript module igv-widgets.js:1". 

![image](https://user-images.githubusercontent.com/65100114/122143662-dd79ff00-ce1f-11eb-8a9b-d2ed5ba1183f.png)

**Comment by jrobinso** [comment]
Sorry, run what server?  How (how did you start it)?  We don't provide a server.

**Comment by feedlord18** [comment]
Sorry, I meant when I started the webapp.

**Comment by jrobinso** [comment]
Again, we don't provide a server.   How did you "start" the webapp?

**Comment by jrobinso** [comment]
Ahh, I see, there is a "start" target in package.json.  Apologies that shouldn't be there, its deprecated.  You will need to provide your own server.

Can I assume you started it with. "npm run start"?

**Comment by feedlord18** [comment]
We started it by "sudo http-server -p 72". It was used before and we didn't make any changes to it.

**Comment by feedlord18** [comment]
It was created by the previous guy working on it and I'm trying to contact him right now. But it was working before.

**Comment by jrobinso** [comment]
You will need to install http-server yourself, its no longer in our package dependencies.   See the http-server documentation for documentation, its not something we distribute, but you need to start it on the web content directory (the "dist" directory if you are building from source).

**Comment by feedlord18** [comment]
So I did npm run start, and it is working on 8080. Probably an issue on out end. Sorry.

**Comment by jrobinso** [comment]
OK that will work for now, but again it was a mistake to even be there.   We don't distribute http-server through igv-webapp anymore.   For the future the equivalent of "npm run start" is below, your initial bug was caused by not including the "dist" directory (the content directory)

```
npx http-server -a localhost dist
```

**Comment by feedlord18** [comment]
got it. Thank you!
