### ISSUE TITLE
Non-informative error message when loading genome without index

### ISSUE THREAD

**Issue by helgathorv** [igvteam/igv-webapp#215]
If you load just a fasta (or fa) file without the index, the error message says: "Genome did not load - invalid file". The user has no idea what that means.

**Comment by turner** [comment]
Here is the current improved wording
![Screen Shot 2021-07-16 at 2 58 26 PM](https://user-images.githubusercontent.com/87169/125996121-a5862795-3184-4f03-8411-6fe55f17c936.png)

**Comment by turner** [comment]
Closed with igv-widgets commit c0041b1f
