### ISSUE TITLE
Error on startup if missing session registry file

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv-webapp#226]
There's an error on startup, seems related to a missing session registry file.   Most installations probably won't use this feature, if its not set in the config it should just be skipped.

<img width="585" alt="Screen Shot 2021-11-22 at 8 44 26 PM" src="https://user-images.githubusercontent.com/933148/142972497-5b1f0be0-d6e0-4495-b98c-31bc1bf1ba4e.png">

**Comment by turner** [comment]
Fixed with commit 0399aa1c in dat_jbrowse_circularview_spike branch
