### ISSUE TITLE
Include table properties in config when loading from ModalTable

### ISSUE THREAD

**Issue by jrobinso** [igvteam/igv-webapp#233]
I'm not sure if this belongs here, or igv-widgets, or both.   When loading from a "ModalTable", e.g. Encode,  include all table properties for the row in the track config wrapped in a property  "metadata".   These properties can then be used in the track description popup (triggered from the track label).   So the track config for the Encode loader would include

```
config.metadata: {
   "Biosample":  "...",
   "Assay Type": " "...",
   etc
}

This should not be restricted to the Encode loader, it should work for user-defined ModalTable loaders as well.

**Comment by turner** [comment]
I've added this in a data-modal PR https://github.com/igvteam/data-modal/pull/21
