### ISSUE TITLE
Support for macFas5

### ISSUE THREAD

**Issue by dany-fu** [igvteam/igv-webapp#236]
Any chance IGV will support macFas5 as a preloaded genome (ie. make it a part of genomes.json) in the near future?

**Comment by jrobinso** [comment]
Just added

**Comment by dany-fu** [comment]
@jrobinso macFas5 seems to have been removed from genomes.json. Could you add it again?

**Comment by dany-fu** [comment]
Thanks, I see it again via the s3 link. However it's not actually committed to `resources/genomes.json` in this repo. Will future commits to this file remove macFas5 again?

**Comment by jrobinso** [comment]
Shouldn't.
