### ISSUE TITLE
Error accessing resource on Dropbox cram

### ISSUE THREAD

**Issue by aardes** [igvteam/igv-webapp#238]
Dear, 

Recently I have issue with loading CRAM files through the online version, File is loaded correctly but when I search for a position it gives me the following error:

Error accessing resource: https://dl.dropboxusercontent.com/********.cram Status: 0

I tried an old version of the javascript code locally as well as the IGV application and the link is correct and I am able to load my cram file and search for the position.

May I kindly ask you to look into this issue?

Thanks in advance
Amin

**Comment by jrobinso** [comment]
Hi,
I can't reproduce the issue.   Here is my test CRAM,  for hg19, jump to gene SLC25A3

cram: https://www.dropbox.com/s/sk1d88s54v06n6u/heart_slc25a3.cram?dl=0
index: https://www.dropbox.com/s/3ngrv2qsrrr07bo/heart_slc25a3.crai?dl=0

Could you share a link to a CRAM file that is giving you an issue?

**Comment by aardes** [comment]
Dear Jim,

Thanks for the fast response, may I have your email address? 

Regards

**Comment by aardes** [comment]
and for your info, I tried different browsers and for the link you shared, I see the exact same error.

<img width="1421" alt="Screenshot 2022-03-07 at 21 10 06" src="https://user-images.githubusercontent.com/12953535/157110466-65c18afd-83f8-4cbe-84c3-76cfb827d486.png">

**Comment by jrobinso** [comment]
That doesn't look like the webapp (igv.org/app),  so I can't really tell what you are using.   Can you try it at https://igv.org/app?

If you need to send a link to private data you can send it to igvteam (at) broadinstitute.org

**Comment by aardes** [comment]
Please have the full screenshot, I am using the igv app.

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/12953535/157111952-6f2b3e0f-5174-4b29-80d8-5a3f15c99824.png">



I've just noticed that it's related to the browser, I tried google chrome and it's working, Safari and Firefox generate this error.

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/12953535/157112261-af955c14-69f3-4a92-b97a-ded135611072.png">

**Comment by jrobinso** [comment]
Ahh, important detail.    We'll look into it.  You say it does work in older versions of igv.js?  What is the latest version you have seen it working?

**Comment by jrobinso** [comment]
We do not have a release tagged v1.6.3.  Where did you get this from?

**Comment by helgathorv** [comment]
@aardes Did you mean v1.6.3 of the IGV-Web App? When I install that version, I see the same problems (ie works in Chrome and not in Safari/Firefox)

**Comment by jrobinso** [comment]
Sorry my mistake, I thought the reference was to IGV version number.  I can't find any version of igv.js going back to version 2.0.0 (2018) that works with Firefox+dropbox.    Looking at the network traffic, Safari and Firefox are issuing "OPTIONS" preflight requests when we include range headers.   This is o.k.,  but dropbox is not including CORS headers in the response to these requests for the browser blocks them.   Chrome on the other hand is not sending OPTIONS requests,  which is a bit odd but the rules for what constitutes a "simple" request, not needing OPTIONS, varies by browser.   I will need to create a test case and open an issue at Dropbox, there doesn't appear to be much we can do about this.

If OTOH,  someone finds an igv.js or igv-webapp that works I can look at what we are doing differently.   But I am not optimistic about that.

**Comment by jrobinso** [comment]
BTW  Firefox+dropbox most definitely worked at some point in the past,  something changed either at Dropbox or with the browsers.    I filed an issue at Dropbox,  unless and until they respond there isn't anything we can do.    

https://www.dropboxforum.com/t5/Dropbox-installs-integrations/CORS-requests-involving-OPTIONS-preflight-failing-from-Firefox/m-p/582217/highlight/false#M118137

**Comment by aardes** [comment]
Thank a lot, I can understand. I will inform the users to use chrome.

**Comment by jrobinso** [comment]
I think this is fixed.  It was a problem at Dropbox.

**Comment by jrobinso** [comment]
Hi,

Dropbox reports they have fixed the problem.   We tested Safari and indeed
it looks fixed.
