### ISSUE TITLE
"error when loading a custom genome [mobx-state-tree] Instance identifier 'trackId' for type 'ReferenceSequenceTrackConfigurationSchema' must be a string or a number"

### ISSUE THREAD

**Issue by nettanetta** [igvteam/igv-webapp#240]
Hi! 
I'm trying to load a custom genome from my google drive and I get the following error:
"[mobx-state-tree] Instance identifier 'trackId' for type 'ReferenceSequenceTrackConfigurationSchema' must be a string or a number". These exact files worked as a reference genome a few weeks ago.
Can you please help me understand what went wrong?
Thanks!
Netta

![image (2)](https://user-images.githubusercontent.com/29280770/162017440-cbe05e4c-bf85-4765-852b-ad8b24e71082.png)

https://drive.google.com/file/d/1HS_rAIftJA00hdJaYGgbnhFMeRd49cpo/view?usp=sharing
https://drive.google.com/file/d/1VVxo1_wSgkwlKy3jWxDalgrY5DzLnwvE/view?usp=sharing

**Comment by helgathorv** [comment]
@turner @jrobinso I've confirmed that these genome files load ok into IGV-Web 1.7.0 (from 12/16/2021), but not 1.9.0 (3/4/2022)or later.  Also, the fact that they are in google drive drive doesn't make a difference. I see the same behavior if I download them and load them via Genome > Local File

**Comment by jrobinso** [comment]
This should be fixed, released as version 2.12.1

**Comment by nettanetta** [comment]
Thanks!!! :)
