### ISSUE TITLE
RefSeq mRNA track for T2T-CHM13v2.0 reference works on IGV web app but not downloaded versions? 

### ISSUE THREAD

**Issue by KL-Cardiff** [igvteam/igv-webapp#243]
Hi
I am viewing data mapped to the human T2T-CHM13v2.0 reference in IGV.  I would like to run the UCSC RefSeq mRNA track in parallel (https://hgdownload.soe.ucsc.edu/hubs/GCA/009/914/755/GCA_009914755.4/bbi/GCA_009914755.4_T2T-CHM13v2.0.xenoRefGene.bb) but I cannot visualise this track on the downloaded IGV version 2.12.3.  The track is visible on the IGV web app, however.  The loading error code I see with the downloaded IGV version is: 'Index 4 out of bounds for length 4'.
Please can you let me know how I can modify the track (.bb file) so that it is compatible with the downloaded IGV version since I would like to work offline?
Many thanks.

**Comment by jrobinso** [comment]
Some changes are required in IGV desktop to support that file,  it will be supported in IGV desktop 2.13.0 which we hope to release the end of this week.

**Comment by KL-Cardiff** [comment]
Amazing, thanks so much, I will look out for the new release.
I am most grateful for your quick and helpful response.

Yours,

Kate
________________________________
