### ISSUE TITLE
error accessing repeat tracks for chm13v2

### ISSUE THREAD

**Issue by jo-mc** [igvteam/igv-webapp#248]
when I try and load in repeat tracks (RMSK: ) I get this message

Error:
Error accessing resource: https://hgdownload.soe.ucsc.edu/hubs/GCA/009/914/755/GCA_009914755.4/bbi/GCA_009914755.4_T2T-CHM13v2.0.rmsk.LINE.bb Status: 0: https://hgdownload.soe.ucsc.edu/hubs/GCA/009/914/755/GCA_009914755.4/bbi/GCA_009914755.4_T2T-CHM13v2.0.rmsk.LINE.bb

https://igv.org/app/   (web)  firefox (latest)  Also tried with google chrome (linux)
running: Linux ubuntu  20.04.4 LTS

I am looking at a small region of chr7, chr7:90,706,352-90,716,351. But get same result for other regions.

**Comment by jrobinso** [comment]
Yes I get that too.  Its possible those file URLs were renamed after initial release, looking into it.

**Comment by jrobinso** [comment]
It looks like those files are gone.   I will be removing them from the menu.   You can load this file, which seems to have all repeat masker classes in one file.   Not as convenient but its the best I can do for now:  https://hgdownload.soe.ucsc.edu/hubs/GCA/009/914/755/GCA_009914755.4/bbi/GCA_009914755.4_T2T-CHM13v2.0.t2tRepeatMasker/chm13v2.0_rmsk.bb

**Comment by jrobinso** [comment]
By "those files" I mean all repeat masker files, other chm13v2 tracks seem o.k.

**Comment by jo-mc** [comment]
thankyou. :)

**Comment by jrobinso** [comment]
A caution on that track, it uses  a new bigbed format that I can't find any documentation on, and who's autosql puzzles me.  In particular block sizes and starts can be negative numbers, which I've never seen before.  So the visual representation of the features from that track in IGV are going to be wrong,  although the genomic extent of each feature should be correct.


https://genome.ucsc.edu/cgi-bin/hgTables?db=hub_3267197_GCA_009914755.4&hgta_group=varRep&hgta_track=hub_3267197_t2tRepeatMasker&hgta_table=hub_3267197_t2tRepeatMasker&hgta_doSchema=describe+table+schema
