### ISSUE TITLE
Cannot upload data to the IGV Web app

### ISSUE THREAD

**Issue by cgrunau** [igvteam/igv-webapp#254]
Dear IGV team
We have data available in https://zenodo.org/record/7113924 of which we would like to share the visualisation via https://igv.org/app/

I tried it out with Dropbox a while ago and it worked, but stopped working a couple of days ago. I uploaded data to Zenodo https://zenodo.org/record/7113924

Still not working

Java-Script console reads:
Failed to load resource: Origin https://igv.org is not allowed by Access-Control-Allow-Origin. Status code: 200

The combination Zenodo + IGV webapp would actually be great. Is there anything we/you can do?

Many thanks
Christoph

**Comment by jrobinso** [comment]
I don't know anything about Zenodo, but Dropbox is working fine for me.  Can you open this shared URL?

https://tinyurl.com/2ezc2yvx

**Comment by jrobinso** [comment]
BTW, a subtle but important distinction -- nothing is uploaded to igv.org/app.   It is in fact downloaded to your computer that is running the application (igv-webapp) that itself is downloaded to igv.org/app.    

Data server requirements re documented here:  https://github.com/igvteam/igv.js/wiki/Data-Server-Requirements.   Dropbox meets these requirements, Zenodo does not appear to be setup for this type of use case.

**Comment by cgrunau** [comment]
> Thank you. Actually https://tinyurl.com/2ezc2yvx is not working at my work place:
![Screenshot 2022-09-28 at 10 05 26](https://user-images.githubusercontent.com/18596218/192724350-524bb5aa-7e23-4bdc-a583-340e0b6c8c77.png)

**Comment by jrobinso** [comment]
That's rather strange.   Is it possible your organization is using a proxy that strips headers from http request headers, or that dropbox access is blocked?  You can investigate this with Chrome "developer tools", or similar tools on other browsers.    To do this first open developer tools in a tab on your browser from the View menu (View > Developer > Developer tools).   Then paste the tiny url in your address bar and go.   After the page loads click the network tab.   Scroll the the file affected and clicked "Headers" on the tab to the left (see screenshot below).   Under response headers you should find the header ```access-control-allow-origin: *```.   Let us know what you find.

<img width="1389" alt="Screen Shot 2022-09-28 at 9 00 07 AM" src="https://user-images.githubusercontent.com/933148/192829399-30bcf244-9e4b-4c28-b654-cfd20371a7d0.png">

**Comment by cgrunau** [comment]
Thank you. The files don't load at all. I found in the XHRs for the dropbox served files: "Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be "dl.dropboxusercontent.com", which could put your confidential information at risk." Definitely a restriction of our university firewall since I can connect over the cell phone. Nevertheless maybe an issue.

**Comment by jrobinso** [comment]
I would suggest raising this issue with your IT department.

**Comment by Oksanak22** [comment]
Hello!
I try to use the https://igv.org/app/. 
My data is a big sorted.bam file and i have converted itt into .bedpe with 

module load bedtools 
bedtools bamtobed -i sorted.bam -bedpe > sorted.bedpe 
But when I uploaded  I don't see anything  
![sorted](https://user-images.githubusercontent.com/99827346/217015317-eb3e9fe6-0abd-4c9c-ac03-c75e28550dcb.JPG)
Could anyone help me with that?
Thank you,

**Comment by jrobinso** [comment]
That does not look like a valid bedpe file,   you can do a web search for bedpe format but the first 6 columns should contain chromosome name, start, end, second chromosome name, start, end.

**Comment by Oksanak22** [comment]
Thank you, @jrobinso for your advices. I see
I have to check the mapping process. Аlthough I used bwa bwasw -b 4 -q 1 -r 200 -T 10 -z 55 to map reads to the genome.

**Comment by Oksanak22** [comment]
Hello, Could you guide me @jrobinso on how to get the proper .bedpe file? I converted bed file to .bedpe with bedtools with the bamtobed function.

**Comment by jrobinso** [comment]
@Oksanak22 Sorry, no, I don't have any experience with those tools.
