### ISSUE TITLE
Question of the maintenance of igv-webapp  

### ISSUE THREAD

**Issue by JosephLaiC** [igvteam/igv-webapp#262]
Thank to the author for developing this tool to make viewing sequence data easier.

I'm wondering is the repository still being maintained ?
I got the same error as the issue as igv-js [#1663](https://github.com/igvteam/igv.js/issues/1633). Will that error be fixed here in the future. Or should I use igv-js instead ?

**Comment by jrobinso** [comment]
Yes its being maintained, have a look at the commit log.  I am working on 1663 now.   I can't say if it will fix your issue or not, but that will be fixed soon.    As this is a duplicate I am closing it.

**Comment by jrobinso** [comment]
igv-js https://github.com/igvteam/igv.js/issues/1633. is fixed
