### ISSUE TITLE
Cannot change the color of coverage track

### ISSUE THREAD

**Issue by 92w7** [igvteam/igv-webapp#264]
Hi there! I'm trying to visualize the coverage info of a bam file, and when i try to change the color of different tracks, i found only the alignment track had color change, but not the coverage track. I can still change the color of the annotation track. I used to be able to make the color change (using the same bam files), so I'm not sure what was the issue. Any suggestion would be appreciated!
<img width="1110" alt="Screen Shot 2023-05-05 at 3 11 51 PM" src="https://user-images.githubusercontent.com/108028729/236577001-e0896b1e-bdca-45a5-b4d1-2fa560f696a6.png">

**Comment by jrobinso** [comment]
OK that looks like a IGV bug, I will investigate.

**Comment by turner** [comment]
@92w7 can you post a session file of this bug. I have not been able to reproduce this bug yet. Thx.

**Comment by helgathorv** [comment]
We were never able to reproduce this and no test case was provided.
