### ISSUE TITLE
Feature Request - Group Autoscale and Default Track Height

### ISSUE THREAD

**Issue by NanoCoreUSA** [igvteam/igv-webapp#265]
Hi,

I've started to use the web app to share genome browser sessions with colleagues. Overall it works great, however I've found myself missing a few features from the desktop version and was wondering if there were any straightforward ways to implement them via the configuration files or making small changes to source code.

- Is there an option to make tracks auto scale as a group (i.e., the 'Group Autoscale' function from the desktop app)? We use this a lot for tracks that have been properly normalized so they can be visually compared. I've figured out how to set the data ranges individually in the config file, but for tracks where the signals have a high / dynamic range it would be helpful for the range to scale relative to the loci being viewed as opposed to manually setting it for the entire track.

- Is it possible to change the default track height to something other than 50? Currently if I manually set the heights and then share the session, the heights revert back to 50 when the link is opened. I've also tried saving the session as a file, but the height attribute also doesn't get automatically stored in the JSON either, so if I want to share exactly what I'm seeing I have to manually edit the JSON file and then share that.

I'm happy to take a stab at implementing these features myself if it's not too complicated, just wanted to check whether they're actually doable first.

**Comment by jrobinso** [comment]
I'll take these separately
 * For group autoscale, its not possible to do this currently from the webapp, however you can do it with igv.js through the track configuration.    See the documentation here, specifically "autoscaleGroup":  https://github.com/igvteam/igv.js/wiki/Wig-Track
 * For the second question, that would be a bug, however I can't reproduce it.  Can you give me some exact steps to reproduce?   In the following shared session, for example, I have manually set the gene track height to 300 (by manually, I mean through the menu):  https://tinyurl.com/2hj4utgv

**Comment by NanoCoreUSA** [comment]
Thanks for the reply, I will have to check out igv.js, I've only used the webapp. For the second issue, I checked your link and it works fine, so I'm thinking I might be using an out-of-date version of the webapp. I will attempt to update it on the server and if it still doesn't work I'll report back.

**Comment by helgathorv** [comment]
Group autoscale is now supported in the newly released igv-web app. 
1. Click on "Select Tracks" to display checkboxes to the left of the tracks.
2. Click in the checkboxes of the tracks you want to group autoscale
3. Click in the gear menu of one of the tracks and select "Group autoscale"
