### ISSUE TITLE
Genome -> URL: Error accessing resource

### ISSUE THREAD

**Issue by Epannec** [igvteam/igv-webapp#269]
Hi,

First of all, thank you for the effort of generating a web-based variant of IGV, this could be very useful for us. However, I seem to have problems when loading our own genomes.

When I try to add my local genomic data, which is hosted on the same instrument and exposed using http-server, I always get an
 `Error accessing resource: *link-to-fai-file" Status 0 ` . I'm confident that the igv-web instance should have access to the file, and even have tried hosting it on a different location, outside the organisation - the error remains nonetheless. 

The `Status 0` doesn't say too much, and I'm kind of very much stuck with this. Are there some expectations of igv-web regarding the r/w access to the fai file, or something that I'm not thinking about? Any advice on how to proceed troubleshooting, would be very much appreciated!

Kind regards,
Erwin

EDIT:
I just tried hosting [chm13v2.fa.fai](https://s3.amazonaws.com/igv.org.genomes/chm13v2.0/chm13v2.0.fa.fai), and loading it together with the default [genomes URL hosted on S3](https://s3.amazonaws.com/igv.org.genomes/chm13v2.0/chm13v2.0.fa). This results in the same error. So basically, whenever I'm providing an alternative URL for the fai file, it gives an error. Any hints would be appreciated - the self-hosted fai file can be found [here ](https://wolkje.casanelwin.be/nextcloud/index.php/s/gbHiPPXDbBg36xG/download/chm13v2.0.fa.fai)(https://wolkje.casanelwin.be/nextcloud/index.php/s/gbHiPPXDbBg36xG/download/chm13v2.0.fa.fai).

EDIT2:
Actually, when I try to load data using Genome -> URL and provide 
`https://s3.amazonaws.com/igv.org.genomes/chm13v2.0/chm13v2.0.fa` and 
`https://s3.amazonaws.com/igv.org.genomes/chm13v2.0/chm13v2.0.fa.fai`
igv-web doesn't complain, but the screen also remains empty:
![image](https://github.com/igvteam/igv-webapp/assets/105773964/ca1d611d-983a-4987-b2d8-c9da4493753e)

So there is obviously something I'm not understanding here. Thank you in advance for educating me :)

**Comment by jrobinso** [comment]
I don't see an empty screen, it looks normal to me.    If you select a chromosome and zoom into base level you should see sequence.

A page loaded with https:// protocol cannot load data vis http:// protocol.  Apologies for the obscure error, that is mostly beyond our control,  but I will look into what can be done.

**Comment by jrobinso** [comment]
Also, in case you missed it,  chm13v2.0 is available
<img width="497" alt="Screen Shot 2023-08-21 at 10 01 05 AM" src="https://github.com/igvteam/igv-webapp/assets/933148/6caf31f7-5a72-429d-a71d-ad6a17e503de">
 from the menu

**Comment by jrobinso** [comment]
That particular error comes from the browser before igv.js even sees the response.   It doesn't matter if you host the file locally or not, or how you downloaded it, you can't use http: protocol from javascript, which igv.js is written in, on a page loaded by https:.    If you need to use http: protocol you can host your own copy of igv-webapp but igv.org will force https:.

Another problem that can cause this is lack of CORS support on the server.   This is another error that occurs before igv.js sees the response.    See https://github.com/igvteam/igv.js/wiki/Data-Server-Requirements. for some info on CORS, or do a web search. (Cross Origin Resource Sharing).   If you host a local copy of igv-webapp on the same server as your data you do not need to configure CORS as it is not a cross-origin request. 

RE log,  you can use the development tools of your browser to examine the console log, and also examine network request and response details.
