### ISSUE TITLE
Read files not shown in IGV web browser

### ISSUE THREAD

**Issue by michellescribner** [igvteam/igv-webapp#277]
Hello,

I've noticed that BAM/BAI files that are properly visualized in the IGV desktop app are not showing the reads in the IGV web browser or IGV on Terra. I have confirmed that I am using the same reference fasta/fasta.fai files and bam/bai files in both instances.

I only see this issue for certain BAM files, others work fine. The BAM files that are not working are somewhat large (300MB) and represent fungal genomes with multiple chromosomes. Perhaps this is a memory issue?

![image](https://github.com/igvteam/igv-webapp/assets/56173868/60674adb-7b0e-4d3d-88ed-2a8d7da9a989)
![image](https://github.com/igvteam/igv-webapp/assets/56173868/e052796e-22f3-4d34-9f81-20123d6e1888)

**Comment by jrobinso** [comment]
I don't think it is memory, and 300 MB is not very large for a BAM file.   I'm not familiar with Terra IGV, is it an embedded web version?

If you could share a session with us I can look into it further.   The easiest way to do that is with the "Share" button.  You can attache the link here, or if you do not want to publish it email it to igv-team@broadinstitute.org.

**Comment by michellescribner** [comment]
Thank you! I have shared the session in an email.

**Comment by jrobinso** [comment]
Thanks, but I haven't seen the email yet.   Did you send it to igv-team@broadinstitute.org?

**Comment by jrobinso** [comment]
Oh, never mind, just got it.

**Comment by jrobinso** [comment]
@michellescribner How as the bam file loaded into igv-web?   The shared session appears to be referencing a local file.  Local files are not sharable, but it should have warned you when making the share URL.   I assumed you loaded this file by URL since you mentioned Terra.

In any event, we need to know how the file was loaded (i.e. by which menu item),  and if it is local or has a URL.

**Comment by jrobinso** [comment]
Well it appears we have a bug that allows you to save a session (share url) with references to local files without warning.  We can't access that BAM file from here, obviously,  if you have a URL to it or can share it some other way please send that to our igv-team email.

**Comment by jrobinso** [comment]
OK thanks, I see the issue.  Its a sequence name mismatch.  In your BAM file the first sequence name, for example, is

PEKT02000007

The corresponding sequence in the fasta file is

PEKT02000007.1

IGV Desktop is, apparently, able to resolve this difference, although to be honest I don't know how and that looks like a bug (in desktop).  

The easiest fix here is probably to rename the sequences in your fasta.   And actually, you just need to rename them in you fasta index.    If you try replacing your fasta index reference with the attached one (after unzipping) you should see the alignments.    
[GCA_002759435.2_Cand_auris_B8441_V2_genomic.fasta.fixed.fai.zip](https://github.com/igvteam/igv-webapp/files/13605293/GCA_002759435.2_Cand_auris_B8441_V2_genomic.fasta.fixed.fai.zip)

**Comment by helgathorv** [comment]
I'm assuming that the above suggestion worked. Feel free to reopen if there are further questions.
