### ISSUE TITLE
How to load NCBI Mmul_10 genome using URL in IGV Web Browser?

### ISSUE THREAD

**Issue by pbuendia** [igvteam/igv-webapp#278]
How do I load NCBI Mmul_10 genome using URL in the IGV Web Browser?
I am trying to avoid downloading and uploading to IGV Web Browser but also wondering what the URL option is for or where it should link to?

This is the NCBI Mmul_10 genome URL:
https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_003339765.1/

Thanks you for your help!

Paty

**Comment by jrobinso** [comment]
In the current release at igv.org/app the URL needs to be to an igv.js genome json file, describe [here] (https://github.com/igvteam/igv.js/wiki).  However we are just finishing testing on the next release which will allow loading of any assembly from the [UCSC genark site](https://hgdownload.soe.ucsc.edu/hubs/).   The URL for Mmul_10 is

https://hgdownload.soe.ucsc.edu/hubs/GCA/011/750/645/GCA_011750645.1/hub.txt

You can try this from https://igv.org/app-test.   There are 2 options for loading the assembly.  Loading from the Genomes | URL option will result in a sequence and annotation track, with other track options available from the "Tracks" menu.   Loading from the Session | URL menu will result in a larger set of initial tracks.   In both cases remaining tracks are available from the "Tracks" menu.   Prior to release these options will probably be consolidated under the "Genomes" menu.

**Comment by jrobinso** [comment]
This has been released, so follow instructions above at https://igv.org/app
