### ISSUE TITLE
Quickly locate a gene through a URL

### ISSUE THREAD

**Issue by jmzhang1911** [igvteam/igv-webapp#282]
Hi IGV team, thank you for developing such an excellent tool.

Due to certain reasons, I wish to quickly locate the position of a specific gene through a URL.
For example, I would like to quickly access the gene NANOG through the URL http://172.16.3.222:8081/chr12:7,787,794-7,799,146 for certain reasons.I don't have much knowledge about web development, so I'm curious if it's possible to achieve this effect by modifying the configuration file. Looking forward to your reply, thank you!

![4911712651716_ pic](https://github.com/igvteam/igv-webapp/assets/52552382/e885cb2f-de2c-4eef-869e-667ba3426810)

**Comment by jrobinso** [comment]
You can set a locus in the configuration file, but you probably know that.   The following URl will work for the initial load, but it will of course cause a page reload

https://igv.org/app/?locus=chr7:55,018,016-55,212,628

**Comment by jmzhang1911** [comment]
"Thank you very much, your response has been very helpful to me. By the way, where can I find documentation for URL routers?"

**Comment by helgathorv** [comment]
see https://github.com/igvteam/igv.js/wiki/Query-Parameters

**Comment by jmzhang1911** [comment]
Got it, thank you very much.
