### ISSUE TITLE
IGV web app broken: 403 error for genomes.json in Amazon S3

### ISSUE THREAD

**Issue by eweitz** [igvteam/igv-webapp#283]
The IGV web app is a remarkably useful resource, and a valuable complement to the more portable igv.js web component.  However, I just noticed that https://igv.org/app seems broken at the moment -- it does not display the igv.js embed, only a header and footer.

When I open browser DevTools Console at that IGV web app page, I see:
```
app.js:450 
GET https://s3.amazonaws.com/igv.org.genomes/genomes.json 403 (Forbidden)
```

Navigating to https://s3.amazonaws.com/igv.org.genomes/genomes.json returns an XML file for the error:
```
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>NV54YQK1CWH84BNN</RequestId>
  <HostId>l22dw2REbdDdBxNxWJ7g0R1NuKAb9LCD/ei4y8GggWm29WIM7MxajIIdeWedSBerU4CXyDj7ivI=</HostId>
</Error>
```

Screenshot:

<img width="1512" alt="IGV_web_app_broken_403_error__2024-04-19" src="https://github.com/igvteam/igv-webapp/assets/1334561/f902ecd7-a75c-4bb1-948d-7d171e649abf">

Is there perhaps some configuration change in Amazon S3 that would fix this?

**Comment by jrobinso** [comment]
Hi @eweitz , this is fixed, my mistake.

**Comment by eweitz** [comment]
Confirmed, thanks for the quick fix!
