### ISSUE TITLE
open igv-webapp site (https://igv.org/app/), but this web is not displayed correctly. 

### ISSUE THREAD

**Issue by sunhuaibo** [igvteam/igv-webapp#284]
Hi IGV team, I try to open igv-webapp site (https://igv.org/app/), but this web is not displayed correctly. 

I use the edge browser, and I also tried chrome browser.

<img width="1214" alt="igv1" src="https://github.com/igvteam/igv-webapp/assets/13502927/a7cc726d-9fa7-4bf3-9740-feff5da33e32">
<img width="1227" alt="igv2" src="https://github.com/igvteam/igv-webapp/assets/13502927/2ec6b2fe-2021-4d50-9c74-dd38051130a7">

Best regards,
sunhuaibo

**Comment by sunhuaibo** [comment]
Is this because I can‘t enable ”Enabling Google access“？

![image](https://github.com/igvteam/igv-webapp/assets/13502927/c09dedb9-a6e8-47e9-a749-db777b4974a0)

**Comment by jrobinso** [comment]
Blocking google access could be a problem,  but the more immediate problem is you aren't able to load many required files, for example the bootstratp css and js.    If you can't load these files you won't be able to use https://igv.org/app.

**Comment by sunhuaibo** [comment]
Thinks

**Comment by jrobinso** [comment]
Closing as there is nothing we can do about this.
