### ISSUE TITLE
Split-screen URL

### ISSUE THREAD

**Issue by OumaimaHamza** [igvteam/igv-webapp#288]
Hello ! 
Adding genomic coordinates in the search box will split up the IGV view to 2 panels 
However when I do share (from the menu bar) >  email,  the shortcut URL doesn't have info about the split screen, so my question is how would the URL look like for a split screen state of the IGV session ? 
Thank you !

**Comment by jrobinso** [comment]
I'm not sure what you are asking, in my testing it does encode the split screen.  For example this URL splits between chr1 and chr2:  https://tinyurl.com/2dbcmajy

Could you post a URL that is not working?

**Comment by OumaimaHamza** [comment]
My bad, it was a problem with our locally hosted implementation of iGV web app. Thanks!
