### ISSUE TITLE
No login prompt

### ISSUE THREAD

**Issue by OumaimaHamza** [igvteam/igv-webapp#292]
Hello 
I am loading data tracks from URL , I got a prompt to enter the link for the bam file and the index file but no login prompt 
When I start zooming in to see the features I get this error 
<img width="1082" alt="Screenshot 2024-06-05 at 3 14 06 PM" src="https://github.com/igvteam/igv-webapp/assets/73792407/699d91b2-598b-4ac2-a4de-d534874e17e8">
I tried with the iGV desktop app and it prompted me to enter my username and password and the tracks were loaded 
Thanks !

**Comment by jrobinso** [comment]
What type of authentication are you using?

**Comment by jrobinso** [comment]
The URL above redirects to a login page.   This is something custom for OICR.  It's possible they have configured your desktop application to support it, but igv-webapp has no knowledge of this.

**Comment by OumaimaHamza** [comment]
It's basic authentication with username and password , I downloaded the iGV desktop app myself , I dont think it's been pre-configured

**Comment by jrobinso** [comment]
And the server is not responding with a basic authentication response in any event.  The request to the "bai" file above returns a 302 redirect to /my.policy,  not a 401 not-authorized response.
