### ISSUE TITLE
Feature Request - Move to next BED entry

### ISSUE THREAD

**Issue by engreitz** [igvteam/igv-webapp#293]
Would it be possible to add to the web app the ability to move to the next BED entry?

In the desktop app, I believe you can use 'Ctrl-F' or something like that to cycle through entries in a given BED track (moving the genomic coordinates to that region)

This functionality is very helpful — would it be possible to add this in the web app as well?  Perhaps it could be an option in the dropdown menu for the BED track

**Comment by jrobinso** [comment]
I'm working on this now, see also https://github.com/igvteam/igv.js/issues/884

**Comment by helgathorv** [comment]
This has been released in IGV-Web 2.0.0. 
First select the track of interest by clicking on "Select Tracks" and then clicking in the checkbox to the left of the track.
Lower case f / b will jump to the next / previous feature, using current zoom level
Upper case F / B will jump to the next / previous feature, and zoom in to the feature
