### ISSUE TITLE
Group autoscale on web app

### ISSUE THREAD

**Issue by SLundregan** [igvteam/igv-webapp#298]
Hi, 

I noticed there has been some work toward implementing track selection and group autoscale on the IGV web app. The option is available on the testing app here https://igv.org/app-test/. 

This feature is very useful but not available on the main web app yet, do you know if/when it will be released?

**Comment by jrobinso** [comment]
We are just finishing testing now, probably by Monday if no issues are found.

**Comment by helgathorv** [comment]
This has now been released
