### ISSUE TITLE
mm39 genome unable to load

### ISSUE THREAD

**Issue by siddharthab** [igvteam/igv-webapp#300]
With the latest update to genomes, the chromSizes URL for mm39 is now "https://hgdownload.soe.ucsc.edu/goldenPath/mm39/database/chromInfo.txt.gz", but the loader function does not uncompress the content and thus loads corrupt chromosome names, which crashes later on.

To test, you can open [igv.org/app](https://igv.org/app), and try to switch to mm39.

**Comment by jrobinso** [comment]
Thanks, it should be fixed now.

**Comment by siddharthab** [comment]
Thanks, can confirm that https://igv.org/genomes/genomes.json now has a working URL.
