### ISSUE TITLE
Google Drive access is blocked by IGV web app

### ISSUE THREAD

**Issue by mcruicks** [igvteam/igv-webapp#304]
I have been accessing data with the IGV web app (https://igv.org/app/) from my Google Drive for a few years but now get the following message when I attempt to load data from Google Drive drop down in "Tracks":

This app is blocked
This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.

<img width="673" alt="Screenshot 2024-09-12 at 4 25 47 PM" src="https://github.com/user-attachments/assets/185acfe2-b9ea-4399-b5b9-50356da352e4">

I have not been able to determine if this is an issue with Google Drive permissions or IGV web app.

**Comment by helgathorv** [comment]
Thanks for letting us know. I have not been able to reproduce this, but one of our colleagues has - so it's not just you.

**Comment by helgathorv** [comment]
@mcruicks Can you try again now.

**Comment by mcruicks** [comment]
Thank you so much - but i still receive the message.
Not sure if this helps, but I am able to access data through DropBox no problem.
I wonder if it is settings on my google drive? I cannot find anyway to alter third party permission though.
Thanks again!

**Comment by jrobinso** [comment]
Could you try clearing your browser cache, then refreshing the igv.org/app page?

**Comment by mcruicks** [comment]
Thank you! This has fixed my problem! much appreciated.
