### ISSUE TITLE
Request: Add dockerfile for quick test drive

### ISSUE THREAD

**Issue by matthdsm** [igvteam/igv-webapp#32]
Hi,

Would it be possible to add a DOCKERFILE to make a quick test drive possible?
Also, license permitting, this would mighty useful for forking/stealing.

Thanks a bunch!

Cheers
M

**Comment by jrobinso** [comment]
License is MIT, and we encourage stealing just give us attribution.   

A docker file would not be very useful since igv-webapp is really just a lot of static files.   There is no server.  A docker file would be equivalent to a zip archive which you can already download.

Have a look at the igv.js readme, specifically the "Developing" section.   I intend to add similar instructions for igv-webapp,    it uses node.js and makes test driving very easy.

**Comment by matthdsm** [comment]
Hi Jim,

Thanks for the info, you may consider this stolen!

Thanks again
M

**Comment by jrobinso** [comment]
Excellent  (evil laugh...)

You are an early adopter, before official release or any documentation,  but here are some tips/warnings.    And, if you deploy a public site send us a pointer,  we like to keep tabs on how these tools are being used.   Also, our sponsors are keenly interested.

If you want to use the Google Picker you'll have to register and obtain a clientID and api key.  Actually the client id might be enough but you get both anyway.   Put them in the appropriate place (Look for CLIENT_ID and API_KEY).    

Ditto if you want to use the URL shortener with the "Share" button,  you'll need a bitly key.    You can also supply your own shortener function.   Everything functions without this you will just have long URLs.

I need to do some refactoring to make the track menus configurable,  but you can probably figure out how to do that.

All of this will be documented before we officially release it.

**Comment by jrobinso** [comment]
One other thing -- the app (index.html) will run as is but requires ES6 support.   This is fine for most browsers, but not some iPhones.   The grunt task builds an ES5 distribution,  which will be the official one (in dist folder).

**Comment by matthdsm** [comment]
Hi Jim,

Thank for the extra pointer. I've got pretty much no idea whatsoever as to what I'm getting into, but I REALLY like the example, so I intend to (try to) figure it out.
If you find the time, some minimal docs would be great, as I'm already having some issues getting it running. I tried following the dev pointers at igv.js, but I think I'm still missing something.

Thank anyway, I'll be keeping a close eye on this.
Cheers
M

**Comment by jrobinso** [comment]
The igv.js examples should work as is -- if not there is a bug in the
instructions.   I assume you're trying to translate those to igv-webapp?

I will have igv-webapp instructions up within a few days,  but if you are
having trouble getting igv.js examples to work open a git issue in that
project.

On Thu, Sep 13, 2018 at 10:45 PM, Matthias De Smet <notifications@github.com

**Comment by matthdsm** [comment]
Yeah, that's what I meant, I was trying to get the webapp to work using the igv.js instructions.
Guess I'll have to curb my enthusiasm for a while ;)
Could you give me a ping when the first release drops? I'd love to help, but I've got zero experience with node or anything more advanced than some basic javascript.

Cheers
M

**Comment by jrobinso** [comment]
Yes, will do @matthdsm ,  and it would be helpful to have you test the instructions.  Did the igv.js instructions work for you (for igv.js that is)?

**Comment by matthdsm** [comment]
Hi Jim,

yes, the instructions for igv.js were very clear and worked fluently. No hiccups whatsoever there.

Cheers
M

**Comment by matthdsm** [comment]
PS: I got the webapp to run using the following steps

```
npm install
grunt
npm run start
```

which started a http-server on port 8080, with the app served at the root level.

Cheers
M

**Comment by jrobinso** [comment]
@matthdsm Good guess, that's exactly how you do it.   We've updated the readme now with instructions for installing, and also instructions for customizing the genome and track menus.

**Comment by matthdsm** [comment]
This project gets more awesome by the day!
Another quick question. In the annotation resources json you use a `ucscservice` filetype. Could you elaborate on/document that? I've looked for it in the igv.js wiki, but didn't find any mentions. Another beta feature?

Thanks for the awesome work!
Cheers
M

**Comment by jrobinso** [comment]
The "ucsc" type is beta, or not even that.   Also it requires a webservice
 (igv.js-flask actually) which we haven't released yet.    I will probably
be replacing those track jsons with standard UCSC file based tracks, its on
my to-do list.  Also add a few more tracks.

On Wed, Sep 19, 2018 at 12:10 AM, Matthias De Smet <notifications@github.com

**Comment by jrobinso** [comment]
Another special track menu type is "ENCODE",  I just added a description of that to the readme.
