### ISSUE TITLE
Support for MyGene/MyVariant.info API

### ISSUE THREAD

**Issue by matthdsm** [igvteam/igv-webapp#59]
Hi Jim

I was wondering if it would be possible to add in support for the [MyGene](http://docs.mygene.info/en/latest/index.html)/[MyVariant](http://docs.myvariant.info/en/latest/index.html) API's as a form of live annotation for vcf files.

It'd be awesome to be able to pull up annotations on a variant at the press of a button.

Thanks
Matthias
xref #58

**Comment by jrobinso** [comment]
Yes that should be straightforward.   Ping this ticket if its not there in a week or so.
