### ISSUE TITLE
igv.org/app CORS prevents loading reference data from broadinstitute.org/AWS

### ISSUE THREAD

**Issue by tmdefreitas** [igvteam/igv-webapp#90]
This isn't necessarily the fault of the web app itself, rather the security settings of igv.org, but it prevents loading any of the example data at igv.org/app/:

<img width="932" alt="Screen Shot 2019-04-01 at 11 35 22 AM" src="https://user-images.githubusercontent.com/3845738/55340267-532d6680-5472-11e9-9aa6-358f95250fe4.png">

**Comment by jrobinso** [comment]
There's something strange going on there because the CORS headers are
definitely set in those buckets.   How did you get this error,  I'm not
able to reproduce it.

**Comment by tmdefreitas** [comment]
Hmmm, somethings strange on my end. I get the error just by going to the site in one of my chrome windows, but if I launch an incognito window (or Firefox), it comes up just fine. Could be one of my browser extensions, or I just need to relaunch chrome. If I can figure out what it was, I'll update this issue.
