### ISSUE TITLE
Can't find an exposed server variable?

### ISSUE THREAD

**Issue by MarkleLab** [igvteam/igv-webapp#96]
Hey! 

I am using your repo and making certain modifications to the app according to my lab's requirements. 

I would like the server to listen on a port for uploads and downloads (of an array of strings if that matters). But, _I can't easily find a server variable that I can add to._ I tried instantiating an Express server but that doesn't work either since it'd have to be on a different port.

What I'm trying to do: I am uploading a csv file, the user interacts with it on the front end, and then I would like to call a python function through the backend that does some quick formatting on the csv, and makes it available for download to the user. 

Issue I'm facing: _I can't figure out how to send some form data and the uploaded file to the backend for further processing._ And, then _send a file back from the backend to the front-end to make the file available for user download_.

I would really appreciate any insight/guidance. Also, I know this is more like a "help wanted" rather than an issue, but I can't change the label of my post.

Thanks!
Milind

**Comment by jrobinso** [comment]
Hi,  igv-webapp is a client application, there is no server, its 100% javascript.   That's why you can't find a server variable.     Nothing is uploaded to igv-webapp, its running in your browser,  upload implies transfer to a server somewhere.   There is nothing out-of-the-box here to support what you are trying to do.

**Comment by MarkleLab** [comment]
Thanks for the clarification @jrobinso! Would you have any recommendations on how to approach this issue?

**Comment by jrobinso** [comment]
Sorry I don't,   you'll need to do custom client and server programming obviously and there are lots of resources out there on that but I don't personally do much server programming.

**Comment by MarkleLab** [comment]
Ok, thanks! I'll close it from my side too.
