### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by MarkleLab** [igvteam/igv-webapp#97]
Hey! 

I've been using your repo and I added in some functionality to it. My node app suddenly stopped working today. The genome browser part of the web app was not loading. I have been using my app without any changes to the code all day today, but the app won't work anymore. 

I cloned a fresh copy of this repo just now to check if that was working, but its not! 
Could you look into this please? Here's a screenshot of what my browser looks like when I started up your application.

<img width="1564" alt="Screen Shot 2019-06-14 at 1 37 43 PM" src="https://user-images.githubusercontent.com/43764863/59527454-9e6be880-8ea9-11e9-94f6-322343ee27da.png">

Best,
Milind

**Comment by turner** [comment]
I am looking at this now.

**Comment by turner** [comment]
Reproducing the build steps - npm install & grunt & npm run start - the app works fine for me.

**Comment by MarkleLab** [comment]
Yayy! Thanks for fixing this. Could you share what the issue was?

**Comment by turner** [comment]
Actually, all I do was git clone and run the above steps. There was nothing to fix.

**Comment by jrobinso** [comment]
@MarkleLab If the app suddenly stopped working something has changed in your environment, the app has not changed.   What do you see in the javascript console?

**Comment by MarkleLab** [comment]
The app is working again now. But if you didn't change the app, then I understand that it might be caused by a change in environment. There weren't any errors in my JS console, which is why I contacted you guys. I'll close this for now though. Will investigate a little by myself. Thanks for helping out!

**Comment by jrobinso** [comment]
@MarkleLab If it happens again I suggest you also look at the network tab,  from Chrome development tools (other browsers might have it also).   Sometimes there are network errors you can see there that do not get logged to the console.
