### ISSUE TITLE
Stability in using cloned copy of repo

### ISSUE THREAD

**Issue by MarkleLab** [igvteam/igv-webapp#99]
Hi!

I cloned this repo, and am using it inside my local server. I understand that any commits you push now won't be reflected inside my server unless I pull a fresh copy of the repo. 

But, I was wondering if there are any code snippets that rely on external resources and might affect stability of IGV Web App. i.e is there any chance that this cloned copy of IGV could crash or suffer downtime due to reliance on external resources?

I might not be explaining my problem very well, so let me know if you need more clarification. I'd be happy to provide it.

**Comment by jrobinso** [comment]
If you pull from a release tag it should be stable.   If you are just pulling the latest from master it might not be.   The master often references the snapshot version of igv.js, e.g.
```
<script src="https://igv.org/web/snapshot/dist/igv.min.js">
```
The release tagged commits, e.g. v1.0.8 uses

```
<script src="https://igv.org/web/snapshot/dist/igv.min.js">
```
<script src='https://cdn.jsdelivr.net/npm/igv@2.2.12/dist/igv.min.js'>
```
If you want a completely stand-alone app you would also need to make copies of all the track and genome resources.
